// Copyright (C) 2020-2022,2024-2025 azumakuniyuki and sisimai development team, All rights reserved.
// This software is distributed under The BSD 2-Clause License.
//  _ _               _   
// | | |__   ___  ___| |_ 
// | | '_ \ / _ \/ __| __|
// | | | | | (_) \__ \ |_ 
// |_|_| |_|\___/|___/\__|

// Package "lhost" provides functions for decoding bounce messages generated by various MTAs such as
// Sendmail, Postfix, OpenSMTPD, some commercial mail servers, and other email services.
package lhost
import "libsisimai.org/sisimai/sis"

// Keep each function for decoding a bounce mail: % grep '^func init' ./lhost/via-*.go | wc -l
var InquireFor = make(map[string]func(*sis.BeforeFact) sis.RisingUnderway, 36)
var Indicators = map[string]uint8 {"deliverystatus": (1 << 1), "message-rfc822": (1 << 2)}

