// Copyright (C) 2020,2024-2026 azumakuniyuki and sisimai development team, All rights reserved.
// This software is distributed under The BSD 2-Clause License.
//  _ _               _      _____          _           
// | | |__   ___  ___| |_   / / _ \ _ __ __| | ___ _ __ 
// | | '_ \ / _ \/ __| __| / / | | | '__/ _` |/ _ \ '__|
// | | | | | (_) \__ \ |_ / /| |_| | | | (_| |  __/ |   
// |_|_| |_|\___/|___/\__/_/  \___/|_|  \__,_|\___|_|   

package lhost
import "strings"

var defaultorder = []string{
	// There are another patterns in the value of "Subject:" header of a bounce mail generated by
	// the following MTAs or ESPs.
	"Exim", "Sendmail", "Exchange2007", "Exchange2003", "AmazonSES", "TrendMicro", "DeutscheTelekom",
	"KDDI", "FML", "Verizon", "ApacheJames", "X2",

	// The following is a fallback list
	"Postfix", "OpenSMTPD", "qmail", "Courier", "MessagingServer", "GoogleWorkspace", "Gmail", "GMX",
	"Zoho", "Domino", "Notes", "IMailServer", "mFILTER", "Activehunter", "MailFoundry", "GoogleGroups",
	"Mimecast", "MailMarshal", "V5sendmail", "EZweb", "Biglobe", "EinsUndEins", "DragonFly", "X1", "X3", "X6",
}

// OrderBySubject returns the order list of MTA modules decided by the first two words of the "Subject": header.
//   Arguments:
//     - title (string): The value of Subject header.
//   Returns:
//     - ([]string): The order list of MTA modules.
func OrderBySubject(title string) []string {
	if title == "" { return []string{} }

	table := map[string][]string {
		"abuse-report":          []string{"ARF"},
		"auto":                  []string{"RFC3834"},
		"auto-reply":            []string{"RFC3834"},
		"automatic-reply":       []string{"RFC3834"},
		"aws-notification":      []string{"AmazonSES"},
		"complaint-about":       []string{"ARF"},
		"delivery-failure":      []string{"Domino", "X2"},
		"delivery-notification": []string{"MessagingServer"},
		"delivery-status":       []string{"OpenSMTPD", "GoogleWorkspace", "Gmail", "GoogleGroups", "AmazonSES", "X3"},
		"dmarc-ietf-dmarc":      []string{"ARF"},
		"email-feedback":        []string{"ARF"},
		"failed-delivery":       []string{"X2"},
		"failure-delivery":      []string{"X2"},
		"failure-notice":        []string{"qmail", "mFILTER", "Activehunter"},
		"loop-alert":            []string{"FML"},
		"mail-could":            []string{"TrendMicro"},
		"mail-delivery":         []string{"Exim", "DragonFly", "GMX", "Zoho", "EinsUndEins", "DeutscheTelekom"},
		"mail-failed":           []string{"DeutscheTelekom"},
		"mail-failure":          []string{"Exim"},
		"mail-system":           []string{"EZweb"},
		"message-delivery":      []string{"MailFoundry"},
		"message-frozen":        []string{"Exim"},
		"non-recapitabile":      []string{"Exchange2007"},
		"non-remis":             []string{"Exchange2007"},
		"notice":                []string{"Courier"},
		"postmaster-email":      []string{"Mimecast"},
		"postmaster-notify":     []string{"Sendmail"},
		"returned-mail":         []string{"Sendmail", "Biglobe", "V5sendmail", "X1"},
		"there-was":             []string{"X6"},
		"undeliverable":         []string{"Exchange2007", "Exchange2003"},
		"undeliverable-mail":    []string{"MailMarshal", "IMailServer"},
		"undeliverable-message": []string{"Notes", "Verizon"},
		"undelivered-mail":      []string{"Postfix", "Zoho"},
		"warning":               []string{"Sendmail", "Exim"},
	}

	// The following order is decided by the first 2 words of Subject: header
	for _, e := range []string{"[", "]", "_"} { title = strings.Replace(title, e, " ", -1) }
	title  = strings.Join(strings.Fields(title), " ")
	buffr := strings.Builder{}; buffr.Grow(len(title))
	words := strings.SplitN(strings.ToLower(title), " ", 3)

	if wi := strings.IndexByte(words[0], ':'); wi > 0 {
		// Undeliverable: ..., notify: ...
		buffr.WriteString(strings.ToLower(title[:wi]))

	} else {
		// Postmaster notify, returned mail, ...
		buffr.WriteString(strings.Join(words[0:2], "-"))
	}
	first := buffr.String()
	for _, e := range []string{`:`, `,`, `*`, `"`} { first = strings.ReplaceAll(first, e, "") }

	if len(table[first]) == 0 /* There is no matched subject */ { return defaultorder }
	if table[first][0] == "ARF" || table[first][0] == "RFC3834" { return table[first] }
	return append(table[first], defaultorder...)
}

