// Copyright (C) 2024-2025 azumakuniyuki and sisimai development team, All rights reserved.
// This software is distributed under The BSD 2-Clause License.
//  _ _               _      ___   _       _            
// | | |__   ___  ___| |_   / / \ | | ___ | |_ ___  ___ 
// | | '_ \ / _ \/ __| __| / /|  \| |/ _ \| __/ _ \/ __|
// | | | | | (_) \__ \ |_ / / | |\  | (_) | ||  __/\__ \
// |_|_| |_|\___/|___/\__/_/  |_| \_|\___/ \__\___||___/

package lhost
import "strings"
import "libsisimai.org/sisimai/v5/sis"
import "libsisimai.org/sisimai/v5/moji"
import "libsisimai.org/sisimai/v5/address"
import "libsisimai.org/sisimai/v5/rfc5322"

func init() {
	// InquireFor[*] decode bounce messages related to or generated by the MTA/ESP of the key name.
	//   Arguments:
	//     - bf (*sis.BeforeFact):  Message entity in progress
	//   Returns:
	//     - (*sis.RisingUnderway): A structure as a staging data that is processed in message.sift() function
	InquireFor["Notes"] = func(bf *sis.BeforeFact) *sis.RisingUnderway {
		// - HCL Notes (Formerly IBM Notes(Formerly Lotus Notes))
		// - https://www.hcl-software.com/notes
		if bf == nil || bf.IsEmpty() == true { return nil }
		if strings.HasPrefix(bf.Headers["subject"][0], "Undeliverable message") == false { return nil }

		boundaries := []string{"------- Returned Message --------"}
		startingof := map[string][]string{"message": []string{"------- Failure Reasons "} }
		messagesof := map[string][]string{
			"networkerror": []string{"Message has exceeded maximum hop count"},
			"userunknown":  []string{
				"User not listed in public Name & Address Book",
				"ディレクトリのリストにありません",
			},
		}
		dscontents := make([]sis.DeliveryMatter, 1); v := &dscontents[0]
		notdecoded := make([]sis.NotDecoded, 0)
		emailparts := rfc5322.Part(&bf.Payload, boundaries, false)
		readcursor := uint8(0)            // Points the current cursor position
		recipients := uint8(0)            // The number of 'Final-Recipient' header

		for e := range strings.Lines(emailparts[0]) {
			// Read error messages and delivery status lines from the head of the email to the
			// previous line of the beginning of the original message.
			e  = strings.TrimRight(e, "\n\r")
			if readcursor == 0 {
				// Beginning of the bounce message or message/delivery-status part
				if strings.HasPrefix(e, startingof["message"][0]) { readcursor |= HereIsDeliveryStatus }
				continue
			}
			if readcursor & HereIsDeliveryStatus == 0 || e == "" { continue }

			// ------- Failure Reasons  --------
			//
			// User not listed in public Name & Address Book
			// kijitora@notes.example.jp
			//
			// ------- Returned Message --------
			if strings.IndexByte(e, '@') > 0 && strings.IndexByte(e, ' ') < 0 {
				// kijitora@notes.example.jp
				if rfc5322.IsEmailAddress(e) == false { continue }
				if len(v.Recipient) > 0 { v = sis.NextDeliveryMatter(&dscontents) }

				v.Recipient = e
				recipients += 1

			} else {
				// Get error messages
				if strings.HasPrefix(e, "-") == false { v.Diagnosis += " " + e }
			}
		}

		if recipients == 0 {
			// Pick an email address from "To:" header of the original message
			if cv := moji.Select(emailparts[1], "\nTo:", "\n", 0); cv != "" {
				dscontents[0].Recipient = address.S3S4(cv); recipients++
			}
		}
		if recipients == 0 { return nil }

		for j, _ := range dscontents {
			// Tidy up the error message in e.Diagnosis, Try to detect the bounce reason.
			e := &dscontents[j]
			e.Diagnosis = moji.Sweep(e.Diagnosis)

			for r := range messagesof {
				// The key name is a bounce reason name
				// Try to find an error message including lower-cased string listed in messagesof
				if moji.ContainsAny(e.Diagnosis, messagesof[r]) { e.Reason = r; break }
			}
		}
		return &sis.RisingUnderway{Digest: dscontents, RFC822: emailparts[1], Errors: notdecoded}
	}
}

