// Copyright (C) 2024-2026 azumakuniyuki and sisimai development team, All rights reserved.
// This software is distributed under The BSD 2-Clause License.
//  _ _               _      ____     __        _                
// | | |__   ___  ___| |_   / /\ \   / /__ _ __(_)_______  _ __  
// | | '_ \ / _ \/ __| __| / /  \ \ / / _ \ '__| |_  / _ \| '_ \ 
// | | | | | (_) \__ \ |_ / /    \ V /  __/ |  | |/ / (_) | | | |
// |_|_| |_|\___/|___/\__/_/      \_/ \___|_|  |_/___\___/|_| |_|

package lhost
import "bytes"
import "strings"
import "libsisimai.org/sisimai/v5/eb"
import "libsisimai.org/sisimai/v5/siba"
import "libsisimai.org/sisimai/v5/moji"
import "libsisimai.org/sisimai/v5/address"
import "libsisimai.org/sisimai/v5/rfc5322"

func init() {
	// InquireFor[*] decode bounce messages related to or generated by the MTA/ESP of the key name.
	//   Arguments:
	//     - bf (*siba.BeforeFact):  Message entity in progress.
	//   Returns:
	//     - (*siba.RisingUnderway): A structure as a staging data that is processed in message.sift() function.
	InquireFor["Verizon"] = func(bf *siba.BeforeFact) *siba.RisingUnderway {
		// - Verizon: https://www.verizon.com/
		if bf == nil || bf.IsEmpty() == true { return nil }

		switch {
			case strings.Contains(bf.Headers["from"][0], "post_master@vtext.com"):
			case moji.Aligned(bf.Headers["from"][0], []string{"sysadmin@", ".vzwpix.com"}):
			default: return nil
		}

		boundaries := [][]byte{[]byte("Original Message:"), []byte("Message details:")}
		nooriginal := false
		startingof := map[string][]string{"message": []string{"Error: "}}
		messagesof := map[string][]string{
			eb.ReUSER: []string{"550 - Requested action not taken: no such user here", "No valid recipients"},
		}

		if bytes.Contains(bf.Payload, boundaries[1]) {
			// Message details:
			//   Subject: Test message
			//   Sent date: Wed Apr 29 23:34:45 GMT 2013
			//   MAIL FROM: nyaaaaaaan@neko.example.org
			//   RCPT TO: may-be-straycat-nyaaaaaan@vtext.com
			//   From: sironeko-nekochan-nyaaaaaaaan-nyan@sabineko.example.com
			// Convert strings above to RFC822 email headers
			nooriginal = true
			bf.Payload = bytes.Replace(bf.Payload, []byte("Sent date: "), []byte("Date: "), 1)
			bf.Payload = bytes.Replace(bf.Payload, []byte("MAIL FROM: "), []byte("Return-Path: "), 1)
			bf.Payload = bytes.Replace(bf.Payload, []byte("RCPT TO: "),   []byte("To: "), 1)
		}

		dscontents := make([]siba.DeliveryMatter, 1); v := &dscontents[0]
		emailparts := rfc5322.Part(bf.Payload, boundaries, false)
		readcursor := uint8(0)

		for e := range strings.Lines(emailparts[0]) {
			// Read error messages and delivery status lines from the head of the email to the
			// previous line of the beginning of the original message.
			e  = strings.TrimRight(e, "\n\r")
			if readcursor == 0 {
				// Beginning of the bounce message or message/delivery-status part
				if strings.HasPrefix(e, startingof["message"][0]) { readcursor |= HereIsDeliveryStatus }
			}
			if readcursor & HereIsDeliveryStatus == 0 || e == "" { continue }

			v.Diagnosis += e
		}

		// Picked the recipient email address from the original message
		if nooriginal { emailparts[1] = strings.ReplaceAll(emailparts[1], "\n  ", "\n") }
		cv := moji.Select(emailparts[1], "\nTo: ", "\n", 0); if cv == "" { return nil }
		dscontents[0].Recipient = address.S3S4(cv)

		for j, _ := range dscontents {
			// Tidy up the error message in e.Diagnosis, Try to detect the bounce reason.
			e := &dscontents[j]
			e.Diagnosis = moji.Sweep(e.Diagnosis)

			for r := range messagesof {
				// The key name is a bounce reason name
				// Try to find an error message including lower-cased string listed in messagesof
				if moji.ContainsAny(e.Diagnosis, messagesof[r]) { e.Reason = r; break }
			}
		}
		return &siba.RisingUnderway{Digest: dscontents, RFC822: emailparts[1]}
	}
}

