// Copyright (C) 2024-2026 azumakuniyuki and sisimai development team, All rights reserved.
// This software is distributed under The BSD 2-Clause License.
//  _ _               _      ______                   _    __        __         _                             
// | | |__   ___  ___| |_   / / ___| ___   ___   __ _| | __\ \      / /__  _ __| | _____ _ __   __ _  ___ ___ 
// | | '_ \ / _ \/ __| __| / / |  _ / _ \ / _ \ / _` | |/ _ \ \ /\ / / _ \| '__| |/ / __| '_ \ / _` |/ __/ _ \
// | | | | | (_) \__ \ |_ / /| |_| | (_) | (_) | (_| | |  __/\ V  V / (_) | |  |   <\__ \ |_) | (_| | (_|  __/
// |_|_| |_|\___/|___/\__/_/  \____|\___/ \___/ \__, |_|\___| \_/\_/ \___/|_|  |_|\_\___/ .__/ \__,_|\___\___|
//                                              |___/                                   |_|                   

package lhost
import "strings"
import "libsisimai.org/sisimai/v5/eb"
import "libsisimai.org/sisimai/v5/siba"
import "libsisimai.org/sisimai/v5/moji"
import "libsisimai.org/sisimai/v5/address"
import "libsisimai.org/sisimai/v5/rfc5322"

func init() {
	// InquireFor[*] decode bounce messages related to or generated by the MTA/ESP of the key name.
	//   Arguments:
	//     - bf (*siba.BeforeFact):  Message entity in progress.
	//   Returns:
	//     - (*siba.RisingUnderway): A structure as a staging data that is processed in message.sift() function.
	InquireFor["GoogleWorkspace"] = func(bf *siba.BeforeFact) *siba.RisingUnderway {
		// - Google Workspace: https://workspace.google.com/
		// - Decode bounce messages from Google Workspace except a bounce mail returned from Google
		// - Workspace due to the remote error (the error message include fields defined in RFC3464)
		if bf == nil || bf.IsEmpty() == true { return nil }

		if moji.ContainsAny(bf.Payload, []string{"\nDiagnostic-Code:", "\nFinal-Recipient:"})  { return nil }
		if strings.Contains(bf.Headers["from"][0], "<mailer-daemon@googlemail.com>")  == false { return nil }
		if strings.Contains(bf.Headers["subject"][0], "Delivery Status Notification") == false { return nil }

		boundaries := []string{"Content-Type: message/rfc822", "Content-Type: text/rfc822-headers"}
		startingof := map[string][]string{
			"message": []string{"** "},
			"error":   []string{"The response was:", "The response from the remote server was:"},
		}
		messagesof := map[string][]string{
			eb.ReUSER: []string{"because the address couldn't be found. Check for typos or unnecessary spaces and try again."},
		}
		dscontents := make([]siba.DeliveryMatter, 1); v := &dscontents[0]
		emailparts := rfc5322.Part(&bf.Payload, boundaries, false)
		recipients, readcursor := uint8(0), uint8(0)

		for e := range strings.Lines(emailparts[0]) {
			// Read error messages and delivery status lines from the head of the email to the
			// previous line of the beginning of the original message.
			e  = strings.TrimRight(e, "\n\r")
			if readcursor == 0 {
				// Beginning of the bounce message or message/delivery-status part
				if strings.HasPrefix(e, startingof["message"][0]) {
					// ** Message not delivered **
					readcursor |= HereIsDeliveryStatus
					v.Diagnosis = e + " "
				}
				continue
			}
			if readcursor & HereIsDeliveryStatus == 0 || e == "" { continue }

			// ** Message not delivered **
			// You're sending this from a different address or alias using the 'Send mail as' feature.
			// The settings for your 'Send mail as' account are misconfigured or out of date. Check those settings and try resending.
			// Learn more here: https://support.google.com/mail/?p=CustomFromDenied
			// The response was:
			// Unspecified Error (SENT_SECOND_EHLO): Smtp server does not advertise AUTH capability
			if strings.HasPrefix(e, "Content-Type:") == false { v.Diagnosis += e + " " }
		}

		if recipients == 0 {
			// Pick the recipient address from the value of To: header of the original message
			// after Content-Type: message/rfc822 field
			if cv := address.S3S4(moji.Select(emailparts[1], "\nTo:", "\n", 0)); cv != "" {
				dscontents[0].Recipient = cv
				recipients++
			}
		}
		if recipients == 0 { return nil }

		for j, _ := range dscontents {
			// Tidy up the error message in e.Diagnosis, Try to detect the bounce reason.
			e := &dscontents[j]

			for r := range messagesof {
				// The key name is a bounce reason name
				// Try to find an error message including lower-cased string listed in messagesof
				if moji.ContainsAny(e.Diagnosis, messagesof[r]) { e.Reason = r; break }
			}
		}
		return &siba.RisingUnderway{Digest: dscontents, RFC822: emailparts[1]}
	}
}

