// Copyright (C) 2024-2025 azumakuniyuki and sisimai development team, All rights reserved.
// This software is distributed under The BSD 2-Clause License.
//  _ _               _      _______ _           _   _           _ _____ _           
// | | |__   ___  ___| |_   / / ____(_)_ __  ___| | | |_ __   __| | ____(_)_ __  ___ 
// | | '_ \ / _ \/ __| __| / /|  _| | | '_ \/ __| | | | '_ \ / _` |  _| | | '_ \/ __|
// | | | | | (_) \__ \ |_ / / | |___| | | | \__ \ |_| | | | | (_| | |___| | | | \__ \
// |_|_| |_|\___/|___/\__/_/  |_____|_|_| |_|___/\___/|_| |_|\__,_|_____|_|_| |_|___/

package lhost
import "strings"
import "libsisimai.org/sisimai/sis"
import "libsisimai.org/sisimai/moji"
import "libsisimai.org/sisimai/address"
import "libsisimai.org/sisimai/rfc5322"
import "libsisimai.org/sisimai/smtp/status"
import "libsisimai.org/sisimai/smtp/command"

func init() {
	// InquireFor[*] decode bounce messages related to or generated by the MTA/ESP of the key name.
	//   Arguments:
	//     - bf (*sis.BeforeFact): Message entity in progress
	//   Returns:
	//     - (sis.RisingUnderway): A structure as a staging data that is processed in message.sift() function
	InquireFor["EinsUndEins"] = func(bf *sis.BeforeFact) sis.RisingUnderway {
		// - 1&1: https://www.1und1.de/
		if bf == nil || bf.Empty() == true                                                 { return sis.RisingUnderway{} }
		if strings.HasPrefix(bf.Headers["from"][0], `"Mail Delivery System"`) == false     { return sis.RisingUnderway{} }
		if bf.Headers["subject"][0] != "Mail delivery failed: returning message to sender" { return sis.RisingUnderway{} }

		boundaries := []string{"--- The header of the original message is following. ---"}
		startingof := map[string][]string{
			"message": []string{"This message was created automatically by mail delivery software"},
			"error":   []string{"For the following reason:"},
		}
		messagesof := map[string][]string{"mesgtoobig": []string{"Mail size limit exceeded"}}

		dscontents := []sis.DeliveryMatter{{}}
		emailparts := rfc5322.Part(&bf.Payload, boundaries, false)
		readcursor := uint8(0)            // Points the current cursor position
		recipients := uint8(0)            // The number of 'Final-Recipient' header
		stringbuff := strings.Builder{}; stringbuff.Grow(len(emailparts[0]) / 2)
		v          := &(dscontents[len(dscontents) - 1])

		for _, e := range(strings.Split(emailparts[0], "\n")) {
			// Read error messages and delivery status lines from the head of the email to the
			// previous line of the beginning of the original message.
			if readcursor == 0 {
				// Beginning of the bounce message or message/delivery-status part
				if strings.HasPrefix(e, startingof["message"][0]) { readcursor |= Indicators["deliverystatus"] }
				continue
			}
			if readcursor & Indicators["deliverystatus"] == 0 || e == "" { continue }

			// The following address failed:
			//
			// general@example.eu
			//
			// For the following reason:
			//
			// Mail size limit exceeded. For explanation visit
			// http://postmaster.1and1.com/en/error-messages?ip=%1s
			if moji.Aligned(e, []string{"@", "."}) && (strings.HasSuffix(e, ":") || strings.IndexByte(e, ' ') < 0 ) {
				// general@example.eu OR
				// the line begin with 4 space characters, end with ":" like "    neko@example.eu:"
				ce := address.S3S4(strings.Trim(e, ":")); if rfc5322.IsEmailAddress(ce) == false { continue }
				if len(v.Recipient) > 0 {
					// There are multiple recipient addresses in the message body.
					dscontents = append(dscontents, sis.DeliveryMatter{})
					v = &(dscontents[len(dscontents) - 1])
				}
				v.Recipient = ce
				recipients += 1

			} else if strings.HasPrefix(e, startingof["error"][0]) {
				// For the following reason:
				v.Diagnosis = e

			} else {
				//  Get error message and append the error message strings
				if v.Diagnosis != "" { v.Diagnosis += " " + e; continue }

				// OR the following format:
				//   neko@example.fr:
				//   SMTP error from remote server for TEXT command, host: ...
				stringbuff.WriteString(" " + e)
			}
		}
		if recipients == 0 { return sis.RisingUnderway{} }

		for j, _ := range dscontents {
			// Get and set other values into sis.DeliveryMatter{}, Try to detect the bounce reason
			e := &(dscontents[j])

			if e.Diagnosis == "" { e.Diagnosis = stringbuff.String() }
			e.Command = command.Find(e.Diagnosis)

			if moji.Aligned(e.Diagnosis, []string{"host: ", " reason:"}) {
				// SMTP error from remote server for TEXT command,
				//   host: smtp-in.orange.fr (193.252.22.65)
				//   reason: 550 5.2.0 Mail rejete. Mail rejected. ofr_506 [506]
				e.Rhost  = moji.Sweep(moji.Select(e.Diagnosis, "host: ", " ", 0))
				e.Status = status.Find(e.Diagnosis, "")

				if strings.Contains(e.Diagnosis, "for TEXT command") { e.Command = "DATA" }
				if strings.Contains(e.Diagnosis, "SMTP error")       { e.Spec    = "SMTP" }
			}
			e.Diagnosis = moji.Sweep(e.Diagnosis)

			for r := range messagesof {
				// The key name is a bounce reason name
				// Try to find an error message including lower-cased string listed in messagesof
				if moji.ContainsAny(e.Diagnosis, messagesof[r]) { e.Reason = r; break }
			}
		}
		return sis.RisingUnderway{ Digest: dscontents, RFC822: emailparts[1] }
	}
}

