// Copyright (C) 2024-2025 azumakuniyuki and sisimai development team, All rights reserved.
// This software is distributed under The BSD 2-Clause License.
//  _ _               _      ____  ______  
// | | |__   ___  ___| |_   / /\ \/ /___ \ 
// | | '_ \ / _ \/ __| __| / /  \  /  __) |
// | | | | | (_) \__ \ |_ / /   /  \ / __/ 
// |_|_| |_|\___/|___/\__/_/   /_/\_\_____|

package lhost
import "strings"
import "libsisimai.org/sisimai/v5/siba"
import "libsisimai.org/sisimai/v5/moji"
import "libsisimai.org/sisimai/v5/rfc5322"
import "libsisimai.org/sisimai/v5/smtp/command"

func init() {
	// InquireFor[*] decode bounce messages related to or generated by the MTA/ESP of the key name.
	//   Arguments:
	//     - bf (*siba.BeforeFact):  Message entity in progress.
	//   Returns:
	//     - (*siba.RisingUnderway): A structure as a staging data that is processed in message.sift() function.
	InquireFor["X2"] = func(bf *siba.BeforeFact) *siba.RisingUnderway {
		// - Unknown MTA #2
		// - Can anyone identify the MTA that produced the set-of-emails/maildir/bsd/lhost-x2-*.eml files?
		if bf == nil || bf.IsEmpty() == true { return nil }

		emailtitle := []string{"Delivery failure", "failure delivery", "failed delivery"}
		switch {
			case strings.Contains(bf.Headers["from"][0], "MAILER-DAEMON@"):
			case moji.HasPrefixAny(bf.Headers["subject"][0], emailtitle):
			default: return nil
		}

		boundaries := []string{"--- Original message follows."}
		startingof := map[string][]string{
			"message": []string{
				"Unable to deliver message to the following address",
				"This Delivery Status Notification is sent from MTA",
			},
		}

		dscontents := make([]siba.DeliveryMatter, 1); v := &dscontents[0]
		emailparts := rfc5322.Part(&bf.Payload, boundaries, false)
		recipients, readcursor := uint8(0), uint8(0)

		for e := range strings.Lines(emailparts[0]) {
			// Read error messages and delivery status lines from the head of the email to the
			// previous line of the beginning of the original message.
			e  = strings.TrimRight(e, "\n\r")
			if readcursor == 0 {
				// Beginning of the bounce message or message/delivery-status part
				if moji.HasPrefixAny(e, startingof["message"]) { readcursor |= HereIsDeliveryStatus }
				continue
			}
			if readcursor & HereIsDeliveryStatus == 0 || e == "" { continue }

			// Message from example.com.
			// Unable to deliver message to the following address(es).
			//
			// <kijitora@example.com>:
			// This user doesn't have a example.com account (kijitora@example.com) [0]
			//
			// --- OR ---
			//
			// This Delivery Status Notification is sent from MTA...
			//
			// Your delivery to the following address has been failed.
			// Please refer to the below for details.
			// ------------------------------------------------------
			//
			// Delivery failed: kijitora@example.co.jp
			// 192.0.2.25 does not like recipient.
			// Remote host said[Response Message]: 550 5.1.1 <kijitora@example.co.jp>:
			//   Recipient address rejected: User unknown in local recipient table
			// Giving up on 192.0.2.25.
			// STEP: RCPT TO
			if (strings.HasPrefix(e, "<")                 && moji.Aligned(e, []string{"<", "@", ">:"})) ||
			   (strings.HasPrefix(e, "Delivery failed: ") && moji.Aligned(e, []string{"failed: ", "@"})) {
				// <kijitora@example.com>:
				// Delivery failed: kijitora@example.co.jp
				if len(v.Recipient) > 0 { v = siba.NextDeliveryMatter(&dscontents) }
				v.Recipient = moji.Select(e, "<", ">", 0)
				if v.Recipient == "" { v.Recipient = moji.Select(e + moji.RHS, ": ", "", 12) }
				recipients += 1

			} else if strings.HasPrefix(e, "STEP: ") {
				// STEP: RCPT TO
				// STEP: DATA SEND
				v.Command = command.Find(e)

			} else if strings.HasPrefix(e, "----") == false {
				// Error message lines like the following:
				// This user doesn't have a example.com account (kijitora@example.com) [0]
				v.Diagnosis += " " + e
			}
		}
		if recipients == 0 { return nil }

		for j, _ := range dscontents {
			// Tidy up the error message in e.Diagnosis, Try to detect the bounce reason.
			e := &dscontents[j]
			e.Diagnosis = moji.Sweep(e.Diagnosis)
		}
		return &siba.RisingUnderway{Digest: dscontents, RFC822: emailparts[1]}
	}
}

