// Copyright (C) 2024-2026 azumakuniyuki and sisimai development team, All rights reserved.
// This software is distributed under The BSD 2-Clause License.
//  _ _               _      ______ __  ____  __
// | | |__   ___  ___| |_   / / ___|  \/  \ \/ /
// | | '_ \ / _ \/ __| __| / / |  _| |\/| |\  / 
// | | | | | (_) \__ \ |_ / /| |_| | |  | |/  \ 
// |_|_| |_|\___/|___/\__/_/  \____|_|  |_/_/\_\

package lhost
import "strings"
import "libsisimai.org/sisimai/v5/siba"
import "libsisimai.org/sisimai/v5/moji"
import "libsisimai.org/sisimai/v5/address"
import "libsisimai.org/sisimai/v5/rfc5322"
import "libsisimai.org/sisimai/v5/smtp/command"

func init() {
	// InquireFor[*] decode bounce messages related to or generated by the MTA/ESP of the key name.
	//   Arguments:
	//     - bf (*siba.BeforeFact):  Message entity in progress.
	//   Returns:
	//     - (*siba.RisingUnderway): A structure as a staging data that is processed in message.sift() function.
	InquireFor["GMX"] = func(bf *siba.BeforeFact) *siba.RisingUnderway {
		// GMX: https://gmx.net/
		if bf == nil || bf.IsEmpty() == true { return nil }

		// Envelope-To: <kijitora@mail.example.com>
		// X-GMX-Antispam: 0 (Mail was not recognized as spam); Detail=V3;
		// X-GMX-Antivirus: 0 (no virus found)
		// X-UI-Out-Filterresults: unknown:0;
		if len(bf.Headers["x-gmx-antispam"]) == 0 { return nil }

		boundaries := []string{"--- The header of the original message is following. ---"}
		startingof := map[string][]string{
			"message": []string{"This message was created automatically by mail delivery software"},
		}
		dscontents := make([]siba.DeliveryMatter, 1); v := &dscontents[0]
		emailparts := rfc5322.Part(&bf.Payload, boundaries, false)
		recipients, readcursor := uint8(0), uint8(0)

		for e := range strings.Lines(emailparts[0]) {
			// Read error messages and delivery status lines from the head of the email to the
			// previous line of the beginning of the original message.
			e  = strings.TrimRight(e, "\n\r")
			if readcursor == 0 {
				// Beginning of the bounce message or message/delivery-status part
				if strings.HasPrefix(e, startingof["message"][0]) { readcursor |= HereIsDeliveryStatus }
				continue
			}
			if readcursor & HereIsDeliveryStatus == 0 || e == "" { continue }

			// This message was created automatically by mail delivery software.
			//
			// A message that you sent could not be delivered to one or more of
			// its recipients. This is a permanent error. The following address
			// failed:
			//
			// "shironeko@example.jp":
			// SMTP error from remote server after RCPT command:
			// host: mx.example.jp
			// 5.1.1 <shironeko@example.jp>... User Unknown
			if strings.IndexByte(e, '@') > 1 && moji.HasPrefixAny(e, []string{`"`, "<"}) {
				// "shironeko@example.jp":
				// ---- OR ----
				// <kijitora@6jo.example.co.jp>
				//
				// Reason:
				// delivery retry timeout exceeded
				if len(v.Recipient) > 0 { v = siba.NextDeliveryMatter(&dscontents) }

				v.Recipient = address.S3S4(strings.Trim(e, ":"))
				recipients += 1

			} else {
				switch {
					// - SMTP error from remote server after RCPT command:
					// - host: mx.example.jp
					case strings.HasPrefix(e, "SMTP error "): v.Command = command.Find(e)
					case strings.HasPrefix(e, "host: "):      v.Rhost   = e[6:]
					default: if e != "" { v.Diagnosis += e + " " } // Get error messages
				}
			}
		}
		if recipients == 0 { return nil }

		for j, _ := range dscontents {
			// Tidy up the error message in e.Diagnosis, Try to detect the bounce reason.
			e := &dscontents[j]
			e.Diagnosis = moji.Sweep(strings.ReplaceAll(e.Diagnosis, "\n", " "))
		}
		return &siba.RisingUnderway{Digest: dscontents, RFC822: emailparts[1]}
	}
}

