// Copyright (C) 2024-2025 azumakuniyuki and sisimai development team, All rights reserved.
// This software is distributed under The BSD 2-Clause License.
//  _ _               _      _______     _           
// | | |__   ___  ___| |_   / /__  /___ | |__   ___  
// | | '_ \ / _ \/ __| __| / /  / // _ \| '_ \ / _ \ 
// | | | | | (_) \__ \ |_ / /  / /| (_) | | | | (_) |
// |_|_| |_|\___/|___/\__/_/  /____\___/|_| |_|\___/ 

package lhost
import "strings"
import "libsisimai.org/sisimai/v5/eb"
import "libsisimai.org/sisimai/v5/siba"
import "libsisimai.org/sisimai/v5/moji"
import "libsisimai.org/sisimai/v5/address"
import "libsisimai.org/sisimai/v5/rfc5322"

func init() {
	// InquireFor[*] decode bounce messages related to or generated by the MTA/ESP of the key name.
	//   Arguments:
	//     - bf (*siba.BeforeFact):  Message entity in progress.
	//   Returns:
	//     - (*siba.RisingUnderway): A structure as a staging data that is processed in message.sift() function.
	InquireFor["Zoho"] = func(bf *siba.BeforeFact) *siba.RisingUnderway {
		// - Zoho Mail: https://www.zoho.com/mail/
		if bf == nil || bf.IsEmpty() || len(bf.Headers["x-zohomail"]) == 0 { return nil }

		boundaries := []string{"\n\nReceived:"}
		startingof := map[string][]string{
			"message": []string{"This message was created automatically by mail delivery"},
		}
		messagesof := map[string][]string{eb.ReEXPR: []string{"Host not reachable"}}
		dscontents := make([]siba.DeliveryMatter, 1); v := &dscontents[0]
		emailparts := rfc5322.Part(&bf.Payload, boundaries, true)
		readcursor := uint8(0)            // Points the current cursor position
		recipients := uint8(0)            // The number of 'Final-Recipient' header

		for e := range strings.Lines(emailparts[0]) {
			// Read error messages and delivery status lines from the head of the email to the
			// previous line of the beginning of the original message.
			e  = strings.TrimRight(e, "\n\r")
			if readcursor == 0 {
				// Beginning of the bounce message or message/delivery-status part
				if strings.HasPrefix(e, startingof["message"][0]) { readcursor |= HereIsDeliveryStatus }
				continue
			}
			if readcursor & HereIsDeliveryStatus == 0 || e == "" { continue }

			// This message was created automatically by mail delivery software.
			// A message that you sent could not be delivered to one or more of its recip=
			// ients. This is a permanent error.=20
			//
			// kijitora@example.co.jp Invalid Address, ERROR_CODE :550, ERROR_CODE :5.1.=
			// 1 <kijitora@example.co.jp>... User Unknown

			// This message was created automatically by mail delivery software.
			// A message that you sent could not be delivered to one or more of its recipients. This is a permanent error.
			//
			// shironeko@example.org Invalid Address, ERROR_CODE :550, ERROR_CODE :Requested action not taken: mailbox unavailable
			if moji.Aligned(e, []string{"@", " ", "ERROR_CODE :"}) || strings.HasPrefix(e, "[Status: ") {
				// kijitora@example.co.jp Invalid Address, ERROR_CODE :550, ERROR_CODE :5.1.=
				// [Status: Error, Address: <kijitora@6kaku.example.co.jp>, ResponseCode 421, , Host not reachable.]
				if len(v.Recipient) > 0 { v = siba.NextDeliveryMatter(&dscontents) }
				v.Recipient  = address.S3S4(e)
				v.Diagnosis += " " + e
				recipients  += 1

			} else {
				// Error message which does not include a recipient email address
				if strings.HasPrefix(e, "-----") == false { v.Diagnosis += " " + e }
			}
		}
		if recipients == 0 { return nil }

		for j, _ := range dscontents {
			// Tidy up the error message in e.Diagnosis, Try to detect the bounce reason.
			e := &dscontents[j]
			e.Diagnosis = moji.Sweep(e.Diagnosis)

			for r := range messagesof {
				// The key name is a bounce reason name
				// Try to find an error message including lower-cased string listed in messagesof
				if moji.ContainsAny(e.Diagnosis, messagesof[r]) { e.Reason = r; break }
			}
		}
		return &siba.RisingUnderway{Digest: dscontents, RFC822: emailparts[1]}
	}
}
