// Copyright (C) 2024-2026 azumakuniyuki and sisimai development team, All rights reserved.
// This software is distributed under The BSD 2-Clause License.
//  _ _               _      _______ _____             _     
// | | |__   ___  ___| |_   / / ____|__  /_      _____| |__  
// | | '_ \ / _ \/ __| __| / /|  _|   / /\ \ /\ / / _ \ '_ \ 
// | | | | | (_) \__ \ |_ / / | |___ / /_ \ V  V /  __/ |_) |
// |_|_| |_|\___/|___/\__/_/  |_____/____| \_/\_/ \___|_.__/ 

package lhost
import "strings"
import "libsisimai.org/sisimai/v5/eb"
import "libsisimai.org/sisimai/v5/siba"
import "libsisimai.org/sisimai/v5/moji"
import "libsisimai.org/sisimai/v5/address"
import "libsisimai.org/sisimai/v5/rfc1894"
import "libsisimai.org/sisimai/v5/rfc5322"
import "libsisimai.org/sisimai/v5/smtp/command"

func init() {
	// InquireFor[*] decode bounce messages related to or generated by the MTA/ESP of the key name.
	//   Arguments:
	//     - bf (*siba.BeforeFact):  Message entity in progress.
	//   Returns:
	//     - (*siba.RisingUnderway): A structure as a staging data that is processed in message.sift() function.
	InquireFor["EZweb"] = func(bf *siba.BeforeFact) *siba.RisingUnderway {
		// - au EZweb: https://www.au.com/mobile/
		if bf == nil || bf.IsEmpty() == true { return nil }

		// Pre-process email headers of NON-STANDARD bounce message au by EZweb, as known as ezweb.ne.jp.
		//   Subject: Mail System Error - Returned Mail
		//   From: <Postmaster@ezweb.ne.jp>
		//   Message-Id: <20110000000000.F000000@lsean.ezweb.ne.jp>
		proceedsto := 0
		if moji.ContainsAny(bf.Headers["from"][0], []string{"Postmaster@ezweb.ne.jp", "Postmaster@au.com"}) { proceedsto++ }
		if moji.ContainsAny(bf.Headers["message-id"][0], []string{".ezweb.ne.jp>", ".au.com>"})             { proceedsto++ }
		if bf.Headers["subject"][0] == "Mail System Error - Returned Mail"                                  { proceedsto++ }
		for _, e := range bf.Headers["received"] {
			//   Received: from ezweb.ne.jp (wmflb12na02.ezweb.ne.jp [222.15.69.197])
			//   Received: from nmomta.auone-net.jp ([aaa.bbb.ccc.ddd]) by ...
			if moji.ContainsAny(e, []string{"ezweb.ne.jp (EZweb Mail) with", ".au.com ("}) { proceedsto++; break }
		}
		if proceedsto < 2 { return nil }

		boundaries := []string{"--------------------------------------------------", "Content-Type: message/rfc822"}
		startingof := map[string][]string{
			"message": []string{"The user(s) ", "Your message ", "Each of the following", "<"},
		}
		unpaiduser := []string{
			// http://www.naruhodo-au.kddi.com/qa3429203.html
			// The recipient may be unpaid user...?
			"The user(s) account is disabled.",
			"The user(s) account is temporarily limited.",
		}
		dscontents := make([]siba.DeliveryMatter, 1); v := &dscontents[0]
		emailparts := rfc5322.Part(&bf.Payload, boundaries, false)
		recipients, readcursor := uint8(0), uint8(0)

		for e := range strings.Lines(emailparts[0]) {
			// Read error messages and delivery status lines from the head of the email to the
			// previous line of the beginning of the original message.
			e  = strings.TrimRight(e, "\n\r")
			if readcursor == 0 {
				// Beginning of the bounce message or message/delivery-status part
				if moji.HasPrefixAny(e, startingof["message"]) { readcursor |= HereIsDeliveryStatus }
			}
			if readcursor & HereIsDeliveryStatus == 0 || e == "" { continue }

			// The user(s) account is disabled.
			//
			// <***@ezweb.ne.jp>: 550 user unknown (in reply to RCPT TO command)
			//
			//  -- OR --
			// Each of the following recipients was rejected by a remote
			// mail server.
			//
			//    Recipient: <******@ezweb.ne.jp>
			//    >>> RCPT TO:<******@ezweb.ne.jp>
			//    <<< 550 <******@ezweb.ne.jp>: User unknown
			if moji.Aligned(e, []string{"<", "@", ">"}) && (strings.Index(e, "Recipient: <") > 1 || strings.HasPrefix(e, "<")) {
				// Recipient: <******@ezweb.ne.jp> OR <***@ezweb.ne.jp>: 550 user unknown ...
				if len(v.Recipient) > 0 { v = siba.NextDeliveryMatter(&dscontents) }
				v.Recipient = address.S3S4(moji.Select(e, "<", ">", 0))
				v.Diagnosis += " " + e
				recipients += 1

			} else {
				if f := rfc1894.Match(e); f > 0 {
					// "e" matched with any field defined in RFC3464
					o := rfc1894.Field(e); if len(o) == 0 { continue }
					v.Update(v.AsRFC1894(o[0]), o[2])

				} else {
					// The line does not begin with a DSN field defined in RFC3464
					if strings.Contains(e, " >>> ") { v.Command = command.Find(e) }
					v.Diagnosis += " " + e
				}
			}
		}
		if recipients == 0 { return nil }

		for j, _ := range dscontents {
			// Check each value of DeliveryMatter{}, try to detect the bounce reason.
			e := &dscontents[j]
			e.Diagnosis = moji.Sweep(e.Diagnosis)

			if e.Command == "" { e.Command = command.Find(e.Diagnosis) }
			if len(bf.Headers["x-spasign"]) > 0 && bf.Headers["x-spasign"][0] == "NG" {
				// Content-Type: text/plain; ..., X-SPASIGN: NG (spamghetti, au by EZweb)
				// Filtered recipient returns message that include 'X-SPASIGN' header
				e.Reason = eb.ReFILT

			} else {
				// There is no X-SPASIGN header or the value of the header is not "NG"
				if moji.ContainsAny(e.Diagnosis, unpaiduser) { e.Reason = eb.ReQUIT }
			}
			if e.Reason != ""                                { continue }
			if strings.Contains(e.Recipient, "@ezweb.ne.jp") { continue }
			if strings.Contains(e.Recipient, "@au.com")      { continue }
			if strings.HasPrefix(e.Diagnosis, "<") { e.Reason = eb.ReUSER }
		}
		return &siba.RisingUnderway{Digest: dscontents, RFC822: emailparts[1]}
	}
}

