// Copyright (C) 2024-2025 azumakuniyuki and sisimai development team, All rights reserved.
// This software is distributed under The BSD 2-Clause License.
//  _ _               _      ____  _______ 
// | | |__   ___  ___| |_   / /\ \/ /___ / 
// | | '_ \ / _ \/ __| __| / /  \  /  |_ \ 
// | | | | | (_) \__ \ |_ / /   /  \ ___) |
// |_|_| |_|\___/|___/\__/_/   /_/\_\____/ 

package lhost
import "slices"
import "strings"
import "libsisimai.org/sisimai/v5/sis"
import "libsisimai.org/sisimai/v5/moji"
import "libsisimai.org/sisimai/v5/rfc1894"
import "libsisimai.org/sisimai/v5/rfc5322"
import "libsisimai.org/sisimai/v5/smtp/command"

func init() {
	// InquireFor[*] decode bounce messages related to or generated by the MTA/ESP of the key name.
	//   Arguments:
	//     - bf (*sis.BeforeFact):  Message entity in progress
	//   Returns:
	//     - (*sis.RisingUnderway): A structure as a staging data that is processed in message.sift() function
	InquireFor["X3"] = func(bf *sis.BeforeFact) *sis.RisingUnderway {
		// - Unknown MTA #3
		// - Can anyone identify the MTA that produced the set-of-emails/maildir/bsd/lhost-x3-*.eml files?
		if bf == nil || bf.IsEmpty()                                                   == true  { return nil }
		if strings.HasPrefix(bf.Headers["from"][0],    "Mail Delivery System")         == false { return nil }
		if strings.HasPrefix(bf.Headers["subject"][0], "Delivery status notification") == false { return nil }

		boundaries := []string{"Content-Type: message/rfc822"}
		startingof := map[string][]string{
			"message": []string{"      This is an automatically generated Delivery Status Notification."},
		}
		permessage := map[string]string{}   // Store values of each Per-Message field
		keystrings := make([]string, 0, 4)  // Key list of permessage
		dscontents := make([]sis.DeliveryMatter, 1); v := &dscontents[0]
		emailparts := rfc5322.Part(&bf.Payload, boundaries, false)
		readcursor := uint8(0)              // Points the current cursor position
		recipients := uint8(0)              // The number of 'Final-Recipient' header

		for e := range strings.Lines(emailparts[0]) {
			// Read error messages and delivery status lines from the head of the email to the
			// previous line of the beginning of the original message.
			e  = strings.TrimRight(e, "\n\r")
			if readcursor == 0 {
				// Beginning of the bounce message or message/delivery-status part
				if strings.HasPrefix(e, startingof["message"][0]) { readcursor |= HereIsDeliveryStatus }
				continue
			}
			if readcursor & HereIsDeliveryStatus == 0 || e == "" { continue }

			// ============================================================================
			//      This is an automatically generated Delivery Status Notification.
			//
			// Delivery to the following recipients failed permanently:
			//
			//   * kijitora@example.com
			//
			//
			// ============================================================================
			//                             Technical details:
			//
			// SMTP:RCPT host 192.0.2.8: 553 5.3.0 <kijitora@example.com>... No such user here
			//
			//
			// ============================================================================
			if moji.Aligned(e, []string{"  * ", "@", "."}) {
				//   * kijitora@example.com
				if len(v.Recipient) > 0 { v = sis.NextDeliveryMatter(&dscontents) }
				v.Recipient = moji.Select(e + moji.RHS, "  * ", "", 0)
				recipients += 1

			} else {
				// Error message lines
				if strings.HasPrefix(e, "SMTP:") {
					// SMTP:RCPT host 192.0.2.8: 553 5.3.0 <kijitora@example.com>... No such user here
					v.Command    = command.Find(e[4:10])
					v.Spec       = "SMTP"
					v.Diagnosis += " " + e

				} else if strings.HasPrefix(e, "Routing: ") {
					// Routing: Could not find a gateway for kijitora@example.co.jp
					v.Diagnosis += " " + e

				} else if f := rfc1894.Match(e); f > 0 {
					// "e" matched with any field defined in RFC3464
					o := rfc1894.Field(e); if len(o) == 0 { continue }
					z := rfc1894.FieldTable[o[0]]

					if o[3] == "addr" {
						// Final-Recipient: rfc822; kijitora@example.jp
						// X-Actual-Recipient: rfc822; kijitora@example.co.jp
						if o[0] == "final-recipient" {
							// Final-Recipient: rfc822; kijitora@example.jp
							if v.Recipient == o[2] { continue }
							if len(v.Recipient) > 0 { v = sis.NextDeliveryMatter(&dscontents) }

							v.Recipient = o[2]
							recipients += 1

						} else {
							// X-Actual-Recipient: rfc822; kijitora@example.co.jp
							v.Alias = o[2]
						}
					} else if o[3] == "code" {
						// # Diagnostic-Code: SMTP; 550 5.1.1 <userunknown@example.jp>... User Unknown
						v.Spec = o[1]
						v.Diagnosis += " " + o[2]

					} else {
						// Other DSN fields defined in RFC3464
						v.Update(v.AsRFC1894(o[0]), o[2]); if f != 1 { continue }

						// Copy the lower-cased member name of DeliveryMatter{} for "permessage"
						permessage[z] = o[2]
						if slices.Contains(keystrings, z) == false { keystrings = append(keystrings, z) }
					}
				}
			}
		}
		if recipients == 0 { return nil }

		for j, _ := range dscontents {
			// Tidy up the error message in e.Diagnosis, Try to detect the bounce reason.
			e := &dscontents[j]
			for _, z := range keystrings {
				// Do not set an empty string into each member of DeliveryMatter{}
				if len(v.Select(z)) > 0 || len(permessage[z]) == 0 { continue }
				e.Update(z, permessage[z])
			}
			e.Diagnosis = moji.Sweep(e.Diagnosis)
		}
		return &sis.RisingUnderway{Digest: dscontents, RFC822: emailparts[1]}
	}
}

