// Copyright (C) 2025-2026 azumakuniyuki and sisimai development team, All rights reserved.
// This software is distributed under The BSD 2-Clause License.
//  _ _               _      ____  __ _                              _   
// | | |__   ___  ___| |_   / /  \/  (_)_ __ ___   ___  ___ __ _ ___| |_ 
// | | '_ \ / _ \/ __| __| / /| |\/| | | '_ ` _ \ / _ \/ __/ _` / __| __|
// | | | | | (_) \__ \ |_ / / | |  | | | | | | | |  __/ (_| (_| \__ \ |_ 
// |_|_| |_|\___/|___/\__/_/  |_|  |_|_|_| |_| |_|\___|\___\__,_|___/\__|
//                                                                       

package lhost
import "slices"
import "strings"
import "libsisimai.org/sisimai/v5/siba"
import "libsisimai.org/sisimai/v5/moji"
import "libsisimai.org/sisimai/v5/address"
import "libsisimai.org/sisimai/v5/rfc1894"
import "libsisimai.org/sisimai/v5/rfc5322"

func init() {
	// InquireFor[*] decode bounce messages related to or generated by the MTA/ESP of the key name.
	//   Arguments:
	//     - bf (*siba.BeforeFact):  Message entity in progress.
	//   Returns:
	//     - (*siba.RisingUnderway): A structure as a staging data that is processed in message.sift() function.
	//   Since:
	//     - v5.5.0
	InquireFor["Mimecast"] = func(bf *siba.BeforeFact) *siba.RisingUnderway {
		// - Mimecast: https://www.mimecast.com/
		if bf == nil || bf.IsEmpty() == true { return nil }

		switch {
			// Subject: [Postmaster] Email Delivery Failure
			// Message-Id: <0123456789-1102117314000@us-mta-25.us.mimecast.lan>
			case strings.Contains(bf.Headers["subject"][0], "Email Delivery Failure"):
			case strings.HasSuffix(bf.Headers["message-id"][0], ".mimecast.lan>"):
			default: return nil
		}

		boundaries := []string{"Content-Type: message/rfc822"} // No such line in lhost-mimecast-*
		startingof := map[string][]string{"message": []string{"-- "}}
		permessage := map[string]string{}   // Store values of each Per-Message field
		keystrings := make([]string, 0, 4)  // Key list of permessage
		dscontents := make([]siba.DeliveryMatter, 1); v := &dscontents[0]
		emailparts := rfc5322.Part(&bf.Payload, boundaries, false)
		recipients, readcursor := uint8(0), uint8(0)

		for e := range strings.Lines(emailparts[0]) {
			// Read error messages and delivery status lines from the head of the email to the
			// previous line of the beginning of the original message.
			e  = strings.TrimRight(e, "\n\r")
			if readcursor == 0 {
				// Beginning of the bounce message or message/delivery-status part
				if moji.HasPrefixAny(e, startingof["message"]) { readcursor |= HereIsDeliveryStatus }
			}
			if readcursor & HereIsDeliveryStatus == 0 || e == "" { continue }

			if strings.HasPrefix(e, "-- ") {
				// An email that you attempted to send to the following address could not be delivered:
				// -- sabineko@neko.ef.example.org
				if cv := moji.Select(e + moji.RHS, "-- ", "", 0); strings.Contains(cv, " ") == false {
					// -- sotoneko@cat.example.com
					if len(v.Recipient) > 0 { v = siba.NextDeliveryMatter(&dscontents) }
					v.Recipient = address.S3S4(cv)
					recipients += 1

				} else {
					// Deal each line begins with "-- " as an error message.
					//   The problem appears to be :
					//   -- Recipient email address is possibly incorrect
					//   Additional information follows :
					//   -- 5.4.1 Recipient address rejected: Access denied. 
					v.Diagnosis += cv + " "
				}
			} else {
				// Lines after Content-Type: message/delivery-status
				f := rfc1894.Match(e); if f > 0 {
					// "e" matched with any field defined in RFC3464
					o := rfc1894.Field(e); if len(o) == 0 { continue }
					z := rfc1894.FieldTable[o[0]]
					v  = siba.TailDeliveryMatter(dscontents)

					if o[3] == "code" {
						// Diagnostic-Code: SMTP; 550 5.1.1 <userunknown@example.jp>... User Unknown
						v.Spec = o[1]
						v.Diagnosis = o[2]

					} else {
						// Other DSN fields defined in RFC3464
						v.Update(v.AsRFC1894(o[0]), o[2]); if f != 1 { continue }

						// Copy the lower-cased member name of DeliveryMatter{} for "permessage"
						permessage[z] = o[2]
						if slices.Contains(keystrings, z) == false { keystrings = append(keystrings, z) }
					}
				}
			}
		}
		if recipients == 0 { return nil }

		for j, _ := range dscontents {
			// Check each value of DeliveryMatter{}, try to detect the bounce reason.
			e := &dscontents[j]

			for _, z := range keystrings {
				// Do not set an empty string into each member of DeliveryMatter{}
				if len(v.Select(z)) > 0 || len(permessage[z]) == 0 { continue }
				e.Update(z, permessage[z])
			}
		}
		return &siba.RisingUnderway{Digest: dscontents, RFC822: emailparts[1]}
	}
}

