// Copyright (C) 2020-2022,2024-2025 azumakuniyuki and sisimai development team, All rights reserved.
// This software is distributed under The BSD 2-Clause License.
//  _ _               _      ______           _    __ _      
// | | |__   ___  ___| |_   / /  _ \ ___  ___| |_ / _(_)_  __
// | | '_ \ / _ \/ __| __| / /| |_) / _ \/ __| __| |_| \ \/ /
// | | | | | (_) \__ \ |_ / / |  __/ (_) \__ \ |_|  _| |>  < 
// |_|_| |_|\___/|___/\__/_/  |_|   \___/|___/\__|_| |_/_/\_\

package lhost
import "slices"
import "strings"
import "strconv"
import "libsisimai.org/sisimai/v5/sis"
import "libsisimai.org/sisimai/v5/moji"
import "libsisimai.org/sisimai/v5/address"
import "libsisimai.org/sisimai/v5/rfc1894"
import "libsisimai.org/sisimai/v5/rfc5322"
import "libsisimai.org/sisimai/v5/smtp/reply"
import "libsisimai.org/sisimai/v5/smtp/status"
import "libsisimai.org/sisimai/v5/smtp/command"
import "libsisimai.org/sisimai/v5/smtp/transcript"

func init() {
	// InquireFor[*] decode bounce messages related to or generated by the MTA/ESP of the key name.
	//   Arguments:
	//     - bf (*sis.BeforeFact):  Message entity in progress
	//   Returns:
	//     - (*sis.RisingUnderway): A structure as a staging data that is processed in message.sift() function
	InquireFor["Postfix"] = func(bf *sis.BeforeFact) *sis.RisingUnderway {
		// - Postfix https://www.postfix.org/
		if bf == nil || bf.IsEmpty() || len(bf.Headers["x-aol-ip"]) > 0 { return nil } // X-AOL-IP: 192.0.2.1

		proceedsto := uint8(0)
		if strings.Index(bf.Headers["subject"][0], "SMTP server: errors from ") > 0 {
			// src/smtpd/smtpd_chat.c:|337: post_mail_fprintf(notice, "Subject: %s SMTP server: errors from %s",
			// src/smtpd/smtpd_chat.c:|338:   var_mail_name, state->namaddr);
			proceedsto = 2

		} else if bf.Headers["subject"][0] == "Undelivered Mail Returned to Sender" {
			// Subject: Undelivered Mail Returned to Sender
			proceedsto = 1
		}
		if proceedsto == 0 { return nil }

		boundaries := []string{"Content-Type: message/rfc822", "Content-Type: text/rfc822-headers"}
		startingof := map[string][][]string{
			// Postfix manual - bounce(5) - http://www.postfix.org/bounce.5.html
			"message": [][]string{
				[]string{"The ", "Postfix "},           // The Postfix program, The Postfix on <os> program
				[]string{"The ", "mail system"},        // The mail system
				[]string{"The ", "program"},            // The <name> pogram
				[]string{"This is the", "Postfix"},     // This is the Postfix program
				[]string{"This is the", "mail system"}, // This is the mail system at host <hostname>
			},
		}

		permessage := map[string]string{}   // Store values of each Per-Message field
		keystrings := make([]string, 0, 4)  // Key list of permessage
		dscontents := make([]sis.DeliveryMatter, 1); v := &dscontents[0]
		emailparts := rfc5322.Part(&bf.Payload, boundaries, false)
		recipients := uint8(0)              // The number of 'Final-Recipient' header
		nomessages := false                 // Delivery report unavailable
		anotherset := map[string]string{}   // Another error information
		commandset := make([]string, 0, 2)  // "in reply to * command" list

		if proceedsto == 2 {
			// The message body starts with "Transcript of session follows."
			transcript := transcript.Rise(emailparts[0], "In:", "Out:")
			if transcript == nil || len(*transcript) == 0 { return nil }

			for _, e := range *transcript {
				// Pick email addresses, error messages, and the last SMTP command.
				v = sis.TailDeliveryMatter(&dscontents)

				if e.Command == "EHLO" || e.Command == "HELO" {
					// Use the argument of EHLO/HELO command as a value of "lhost"
					v.Lhost = e.Argument

				} else if e.Command == "MAIL" {
					// Set the argument of "MAIL" command to pseudo To: header of the original message
					if len(emailparts[1]) == 0 { emailparts[1] += "To: " + e.Argument + "\n" }

				} else if e.Command == "RCPT" {
					// RCPT TO: <...>
					if len(v.Recipient) > 0 { v = sis.NextDeliveryMatter(&dscontents) }
					v.Recipient = e.Argument
					recipients += 1
				}
				if reply, nyaan := strconv.ParseUint(e.Response.Reply, 10, 16); nyaan != nil || reply < 400 { continue }

				commandset = append(commandset, e.Command)
				if len(v.Diagnosis) == 0 { v.Diagnosis = strings.Join(e.Response.Text, " ") }
				if len(v.ReplyCode) == 0 { v.ReplyCode = e.Response.Reply  }
				if len(v.Status)    == 0 { v.Status    = e.Response.Status }
			}
		} else {
			// The message body is a general bounce mail message of Postfix
			readcursor := uint8(0)              // Points the current cursor position
			readslices := make([]string, 1, 32) // Copy each line for later reference

			j := -1; for e := range strings.Lines(emailparts[0]) {
				// Read error messages and delivery status lines from the head of the email to the
				// previous line of the beginning of the original message.
				j++; e = strings.TrimRight(e, "\n\r")
				readslices = append(readslices, e) // Save the current line for the next loop

				if readcursor == 0 {
					// Beginning of the bounce message or message/delivery-status part
					for _, a := range startingof["message"] {
						if moji.Aligned(e, a) { readcursor |= HereIsDeliveryStatus; break }
					}
					continue
				}
				if readcursor & HereIsDeliveryStatus == 0 { continue }

				if f := rfc1894.Match(e); f > 0 {
					// "e" matched with any field defined in RFC3464
					o := rfc1894.Field(e); if len(o) == 0 { continue }
					z := rfc1894.FieldTable[o[0]]
					v  = sis.TailDeliveryMatter(&dscontents)

					if o[3] == "addr" {
						// Final-Recipient: rfc822; kijitora@example.jp
						// X-Actual-Recipient: rfc822; kijitora@example.co.jp
						if o[0] == "final-recipient" {
							// Final-Recipient: rfc822; kijitora@example.jp
							if len(v.Recipient) > 0 { v = sis.NextDeliveryMatter(&dscontents) }
							v.Recipient = o[2]
							recipients += 1

						} else {
							// X-Actual-Recipient: rfc822; kijitora@example.co.jp
							v.Alias = o[2]
						}
					} else if o[3] == "code" {
						// Diagnostic-Code: SMTP; 550 5.1.1 <userunknown@example.jp>... User Unknown
						v.Spec = o[1]; if strings.ToUpper(o[1]) == "X-POSTFIX" { v.Spec = "SMTP" }
						v.Diagnosis = o[2]

					} else {
						// Other DSN fields defined in RFC3464
						v.Update(v.AsRFC1894(o[0]), o[2]); if f != 1 { continue }

						// Copy the lower-cased member name of DeliveryMatter{} for "permessage"
						permessage[z] = o[2]
						if slices.Contains(keystrings, z) == false { keystrings = append(keystrings, z) }
					}
				} else {
					// If you do so, please include this problem report. You can
					// delete your own text from the attached returned message.
					//
					//           The mail system
					//
					// <userunknown@example.co.jp>: host mx.example.co.jp[192.0.2.153] said: 550
					// 5.1.1 <userunknown@example.co.jp>... User Unknown (in reply to RCPT TO command)
					if strings.HasPrefix(readslices[j], "Diagnostic-Code:") && strings.HasPrefix(e, " ") {
						// Continued line of the value of Diagnostic-Code field
						v.Diagnosis += " " + moji.Sweep(e)
						readslices[j + 1] = "Diagnostic-Code: " + e

					} else if moji.Aligned(e, []string{"X-Postfix-Sender:", "rfc822;", "@"}) {
						// X-Postfix-Sender: rfc822; shironeko@example.org
						emailparts[1] += "X-Postfix-Sender: " + strings.Trim(strings.SplitN(e, ";", 2)[1], " ") + "\n"

					} else {
						// Alternative error messages and recipients
						if strings.Contains(e, "(in reply to ") || strings.Contains(e, "command)") {
							// Find an SMTP command from a string like the following:
							// 5.1.1 <userunknown@example.co.jp>... User Unknown (in reply to RCPT TO
							if cv := command.Find(e); len(cv) > 0 { commandset = append(commandset, cv) }
							if len(anotherset["diagnosis"]) > 0   { anotherset["diagnosis"] += " " + e  }

						} else if moji.Aligned(e, []string{"<", "@", ">", "(expanded from <", "):"}) {
							// <r@example.ne.jp> (expanded from <kijitora@example.org>): user ...
							// OR
							// <kijitora@exmaple.jp>: ...
							anotherset["recipient"] = address.S3S4(moji.Select(e, "<", "< ", 0))
							anotherset["alias"]     = address.S3S4(moji.Select(e, "(expanded from ", "):", 0))
							if cv := moji.Select(e + moji.RHS, ">): ", "", 0); cv != "" { anotherset["diagnosis"] = cv }

						} else if strings.HasPrefix(e, "<") && moji.Aligned(e, []string{"<", "@", ">:"}) {
							// <kijitora@exmaple.jp>: ...
							anotherset["recipient"] = moji.Select(e, "<", ">:", 0)
							anotherset["diagnosis"] = moji.Select(e + moji.RHS, ">:", "", 2)

						} else if strings.Contains(e, "--- Delivery report unavailable ---") {
							// postfix-3.1.4/src/bounce/bounce_notify_util.c
							// bounce_notify_util.c:602|if (bounce_info->log_handle == 0
							// bounce_notify_util.c:602||| bounce_log_rewind(bounce_info->log_handle)) {
							// bounce_notify_util.c:602|if (IS_FAILURE_TEMPLATE(bounce_info->template)) {
							// bounce_notify_util.c:602|    post_mail_fputs(bounce, "");
							// bounce_notify_util.c:602|    post_mail_fputs(bounce, "\t--- delivery report unavailable ---");
							// bounce_notify_util.c:602|    count = 1;              /* xxx don't abort */
							// bounce_notify_util.c:602|}
							// bounce_notify_util.c:602|} else {
							nomessages = true

						} else {
							// Get the error message continued from the previous line
							if len(anotherset["diagnosis"]) == 0 { continue }
							if strings.HasPrefix(e, "    ") { anotherset["diagnosis"] += " " + strings.Trim(e[4:], " ") }
						}
					}
				} // End of message/delivery-status
			}
		}

		if recipients == 0 {
			// Fallback: get a recipient address from error messages
			if len(anotherset["recipient"]) > 0 {
				// Set a recipient address saved in "anotherset"
				v.Recipient = anotherset["recipient"]
				recipients += 1

			} else if nomessages == true {
				// Get a recipient address from message/rfc822 part if the delivery report was unavailable:
				// "--- Delivery report unavailable ---"
				if cv := address.S3S4(moji.Select(emailparts[1], "\nTo: ", "\n", 0)); cv != "" {
					// Try to get a recipient address from To: field in the original message at message/rfc822 part
					sis.TailDeliveryMatter(&dscontents).Recipient = cv
					recipients += 1
				}
			}
		}
		if recipients == 0 { return nil }

		for j, _ := range dscontents {
			// Set default values stored in "permessage" if each value in "dscontents" is empty.
			e := &dscontents[j]
			for _, z := range keystrings {
				// Do not set an empty string into each member of DeliveryMatter{}
				if len(v.Select(z)) > 0 || len(permessage[z]) == 0 { continue }
				e.Update(z, permessage[z])
			}

			if len(anotherset["diagnosis"]) > 0 {
				// Copy alternative error message to e.Diagnosis
				anotherset["diagnosis"] = moji.Sweep(anotherset["diagnosis"])
				if len(e.Diagnosis) == 0 { e.Diagnosis = anotherset["diagnosis"] }

				if moji.ContainsOnlyNumbers(e.Diagnosis) {
					// Override the value of diagnostic code message when the value of e.Diagnosis
					// contains only numbers
					e.Diagnosis = anotherset["diagnosis"]

				} else {
					// More detailed error message is in anotherset
					as := "" // The value of SMTP Status Code picked from anotherset["diagnosis"]
					ar := "" // The value of SMTP  Reply Code picked from anotherset["diagnosis"]

					if e.Status == "" || strings.HasSuffix(e.Status, ".0.0") {
						// Check the value of D.S.N. in "anotherset"
						// The delivery status code is neither an empty nor *.0.0
						as = status.Find(anotherset["diagnosis"], "")
						if as != "" && strings.HasSuffix(as, ".0.0") == false { e.Status = as }
					}

					if e.ReplyCode == "" || strings.HasSuffix(e.ReplyCode, "00") {
						// Check the value of the SMTP reply code in anotherset
						// The SMTP reply code is neither an empty nor *00 
						ar = reply.Find(anotherset["diagnosis"], "")
						if ar != "" && strings.HasSuffix(ar, "00") == false { e.ReplyCode = ar }
					}

					for {
						// Replace e.Diagnosis with the value of anotherset["diagnosis"] when all
						// the following conditions have not matched.
						if len(as + ar) == 0                                       { break }
						if len(anotherset["diagnosis"]) < len(e.Diagnosis)         { break }
						if strings.Index(anotherset["diagnosis"], e.Diagnosis) < 0 { break }

						e.Diagnosis = anotherset["diagnosis"]; break
					}
				}
			}
			e.Diagnosis = moji.Sweep(e.Diagnosis)

			if len(commandset) > 0 {
				// Set an SMTP command name picked from the error message
				e.Command = commandset[0]

			} else {
				// There is no SMTP command
				if e.Command = command.Find(e.Diagnosis); e.Command == "" {
					// <kijitora@example.org>: host r2.example.org[198.51.100.18] refused to talk to me:
					if strings.Contains(e.Diagnosis, "refused to talk to me:") { e.Command = "HELO" }
				}
			}
			if e.Spec != "" { continue }
			if moji.Aligned(e.Diagnosis, []string{"host ", " said:"}) { e.Spec = "SMTP" }
		}
		return &sis.RisingUnderway{Digest: dscontents, RFC822: emailparts[1]}
	}
}

