// Copyright (C) 2024-2025 azumakuniyuki and sisimai development team, All rights reserved.
// This software is distributed under The BSD 2-Clause License.
//  _ _               _      ______  _       _       _          
// | | |__   ___  ___| |_   / / __ )(_) __ _| | ___ | |__   ___ 
// | | '_ \ / _ \/ __| __| / /|  _ \| |/ _` | |/ _ \| '_ \ / _ \
// | | | | | (_) \__ \ |_ / / | |_) | | (_| | | (_) | |_) |  __/
// |_|_| |_|\___/|___/\__/_/  |____/|_|\__, |_|\___/|_.__/ \___|
//                                     |___/                    

package lhost
import "strings"
import "libsisimai.org/sisimai/v5/eb"
import "libsisimai.org/sisimai/v5/siba"
import "libsisimai.org/sisimai/v5/moji"
import "libsisimai.org/sisimai/v5/rfc5322"

func init() {
	// InquireFor[*] decode bounce messages related to or generated by the MTA/ESP of the key name.
	//   Arguments:
	//     - bf (*siba.BeforeFact):  Message entity in progress.
	//   Returns:
	//     - (*siba.RisingUnderway): A structure as a staging data that is processed in message.sift() function.
	InquireFor["Biglobe"] = func(bf *siba.BeforeFact) *siba.RisingUnderway {
		// - BIGLOBE: https://www.biglobe.ne.jp
		if bf == nil || bf.IsEmpty() == true                               { return nil }
		if strings.Contains(bf.Headers["from"][0], "postmaster@") == false { return nil }
		if strings.Index(bf.Headers["subject"][0], "Returned mail:") != 0  { return nil }

		jpprovider := []string{"biglobe", "inacatv", "tmtv", "ttv"}
		proceedsto := false; for _, e := range jpprovider {
			// The From: header should contain one of domain above
			if strings.Contains(bf.Headers["from"][0], "@" + e + ".ne.jp") { proceedsto = true; break }
		}
		if proceedsto == false { return nil }

		boundaries := []string{"Content-Type: message/rfc822"}
		startingof := map[string][]string{
			"message": []string{"   ----- The following addresses had delivery problems -----"},
			"error":   []string{"   ----- Non-delivered information -----"},
		}
		messagesof := map[string][]string{
			eb.ReFILT: []string{"Mail Delivery Failed... User unknown"},
			eb.ReFULL: []string{"The number of messages in recipient's mailbox exceeded the local limit."},
		}

		dscontents := make([]siba.DeliveryMatter, 1); v := &dscontents[0]
		emailparts := rfc5322.Part(&bf.Payload, boundaries, false)
		readcursor := uint8(0)            // Points the current cursor position
		recipients := uint8(0)            // The number of 'Final-Recipient' header

		for e := range strings.Lines(emailparts[0]) {
			// Read error messages and delivery status lines from the head of the email to the
			// previous line of the beginning of the original message.
			e  = strings.TrimRight(e, "\n\r")
			if readcursor == 0 {
				// Beginning of the bounce message or message/delivery-status part
				if strings.HasPrefix(e, startingof["message"][0]) { readcursor |= HereIsDeliveryStatus }
				continue
			}
			if readcursor & HereIsDeliveryStatus == 0 || e == "" { continue }

			// This is a MIME-encapsulated message.
			//
			// ----_Biglobe000000/00000.biglobe.ne.jp
			// Content-Type: text/plain; charset="iso-2022-jp"
			//
			//    ----- The following addresses had delivery problems -----
			// ********@***.biglobe.ne.jp
			//
			//    ----- Non-delivered information -----
			// The number of messages in recipient's mailbox exceeded the local limit.
			//
			// ----_Biglobe000000/00000.biglobe.ne.jp
			// Content-Type: message/rfc822
			//
			if strings.IndexByte(e, '@') > 1 && strings.IndexByte(e, ' ') < 0 {
				//    ----- The following addresses had delivery problems -----
				// ********@***.biglobe.ne.jp
				if rfc5322.IsEmailAddress(e) == false { continue }
				if len(v.Recipient) > 0 { v = siba.NextDeliveryMatter(&dscontents) }

				v.Recipient = e
				recipients += 1

			} else {
				// The boundary string or the error messages
				if strings.Contains(e, "--") == false { v.Diagnosis += e + " " }
			}
		}
		if recipients == 0 { return nil }

		for j, _ := range dscontents {
			// Tidy up the error message in e.Diagnosis, Try to detect the bounce reason.
			e := &dscontents[j]
			e.Diagnosis = moji.Sweep(e.Diagnosis)

			for r := range messagesof {
				// The key name is a bounce reason name
				// Try to find an error message including lower-cased string listed in messagesof
				if moji.ContainsAny(e.Diagnosis, messagesof[r]) { e.Reason = r; break }
			}
		}

		return &siba.RisingUnderway{Digest: dscontents, RFC822: emailparts[1]}
	}
}

