// Copyright (C) 2024-2026 azumakuniyuki and sisimai development team, All rights reserved.
// This software is distributed under The BSD 2-Clause License.
//  _ _               _      __                    _ _ 
// | | |__   ___  ___| |_   / /_ _ _ __ ___   __ _(_) |
// | | '_ \ / _ \/ __| __| / / _` | '_ ` _ \ / _` | | |
// | | | | | (_) \__ \ |_ / / (_| | | | | | | (_| | | |
// |_|_| |_|\___/|___/\__/_/ \__, |_| |_| |_|\__,_|_|_|
//                              |_|                    

package lhost
import "slices"
import "strings"
import "libsisimai.org/sisimai/v5/eb"
import "libsisimai.org/sisimai/v5/siba"
import "libsisimai.org/sisimai/v5/moji"
import "libsisimai.org/sisimai/v5/rfc5322"
import "libsisimai.org/sisimai/v5/smtp/command"

func init() {
	// InquireFor[*] decode bounce messages related to or generated by the MTA/ESP of the key name.
	//   Arguments:
	//     - bf (*siba.BeforeFact):  Message entity in progress.
	//   Returns:
	//     - (*siba.RisingUnderway): A structure as a staging data that is processed in message.sift() function.
	InquireFor["qmail"] = func(bf *siba.BeforeFact) *siba.RisingUnderway {
		// - qmail: https://cr.yp.to/qmail.html
		if bf == nil || bf.IsEmpty() == true { return nil }

		emailtitle := []string{
			"failure notice", // qmail-send.c:Subject: failure notice\n\
			"Failure Notice", // Yahoo
		}
		switch {
			// Pre process email headers and the body part of the message which generated by qmail.
			// see https://cr.yp.to/qmail.html
			// - Received: (qmail 2222 invoked for bounce);29 Apr 2017 23:34:45 +0900
			// - Received: (qmail 2202 invoked from network); 29 Apr 2018 00:00:00 +0900
			case slices.Contains(emailtitle, bf.Headers["subject"][0]):
			case moji.IsContained("(qmail ", bf.Headers["received"]):
			default: return nil
		}

		boundaries := []string{
			// qmail-send.c:qmail_puts(&qqt,*sender.s ? "--- Below this line is a copy of the message.\n\n" :...
			"--- Below this line is a copy of the message.",     // qmail-1.03
			"--- Below this line is a copy of the mail header.",
			"--- Below the next line is a copy of the message.", // The followings are the qmail clone
			"--- Mensaje original adjunto.",
			"Content-Type: message/rfc822",
			"Original message follows.",
		}
		startingof := map[string][]string{
			//  qmail-remote.c:248|    if (code >= 500) {
			//  qmail-remote.c:249|      out("h"); outhost(); out(" does not like recipient.\n");
			//  qmail-remote.c:265|  if (code >= 500) quit("D"," failed on DATA command");
			//  qmail-remote.c:271|  if (code >= 500) quit("D"," failed after I sent the message");
			//
			// Characters: K,Z,D in qmail-qmqpc.c, qmail-send.c, qmail-rspawn.c
			//  K = success, Z = temporary error, D = permanent error
			"error":   []string{"Remote host said:"},
			"message": []string{
				"Hi. This is the qmail", // qmail-send.c:Hi. This is the qmail-send program at ");
				"He/Her is not ",        // The followings are the qmail clone
				"unable to deliver your message to the following addresses",
				"Su mensaje no pudo ser entregado",
				"Sorry, we were unable to deliver your message to the following address",
				"This is the machine generated message from mail service",
				"This is the mail delivery agent at",
				"Unable to deliver message to the following address",
				"unable to deliver your message to the following addresses",
				"Unfortunately, your mail was not delivered to the following address:",
				"Your mail message to the following address",
				"Your message to the following addresses",
				"We're sorry.",
			},
			"rhost":   []string{"Giving up on ", "Connected to ", "remote host "},
		}
		commandset := map[string][]string{
			// Error text regular expressions which defined in qmail-remote.c
			// qmail-remote.c:225|  if (smtpcode() != 220) quit("ZConnected to "," but greeting failed");
			eb.CeCONN: []string{" but greeting failed."},

			// qmail-remote.c:231|  if (smtpcode() != 250) quit("ZConnected to "," but my name was rejected");
			eb.CeEHLO: []string{" but my name was rejected."},

			// qmail-remote.c:238|  if (code >= 500) quit("DConnected to "," but sender was rejected");
			// reason = rejected
			eb.CeMAIL: []string{" but sender was rejected."},

			// qmail-remote.c:249|  out("h"); outhost(); out(" does not like recipient.\n");
			// qmail-remote.c:253|  out("s"); outhost(); out(" does not like recipient.\n");
			// reason = userunknown
			eb.CeRCPT: []string{" does not like recipient."},

			// qmail-remote.c:265|  if (code >= 500) quit("D"," failed on DATA command");
			// qmail-remote.c:266|  if (code >= 400) quit("Z"," failed on DATA command");
			// qmail-remote.c:271|  if (code >= 500) quit("D"," failed after I sent the message");
			// qmail-remote.c:272|  if (code >= 400) quit("Z"," failed after I sent the message");
			eb.CeDATA: []string{" failed on DATA command", " failed after I sent the message"},
		}
		messagesof := map[string][]string{
			// notqmail 1.08 returns the following error message when the destination MX is NullMX
			eb.Re00MX: []string{"Sorry, I couldn't find a mail exchanger or IP address"},
			eb.ReUSER: []string{"no mailbox here by that name"},
		}

		dscontents := make([]siba.DeliveryMatter, 1); v := &dscontents[0]
		emailparts := rfc5322.Part(&bf.Payload, boundaries, false)
		anotherone := []string{""}        // Keeping another error messages
		rightindex, recipients, readcursor := uint8(0), uint8(0), uint8(0)

		for e := range strings.Lines(emailparts[0]) {
			// Read error messages and delivery status lines from the head of the email to the
			// previous line of the beginning of the original message.
			e  = strings.TrimRight(e, "\n\r")
			if readcursor == 0 {
				// Beginning of the bounce message or message/delivery-status part
				if moji.ContainsAny(e, startingof["message"]) { readcursor |= HereIsDeliveryStatus }
				continue
			}
			if readcursor & HereIsDeliveryStatus == 0 || e == "" { continue }

			// <kijitora@example.jp>:
			// 192.0.2.153 does not like recipient.
			// Remote host said: 550 5.1.1 <kijitora@example.jp>... User Unknown
			// Giving up on 192.0.2.153.
			if strings.HasPrefix(e, "<") && moji.Aligned(e, []string{"<", "@", ">:"}) {
				// <kijitora@example.jp>:
				if len(v.Recipient) > 0 {
					// There are multiple recipient addresses in the message body.
					v          = siba.NextDeliveryMatter(&dscontents)
					anotherone = append(anotherone, "")
					rightindex++
				}
				v.Recipient = moji.Select(e, "<", ">:", 0)
				recipients += 1

			} else if len(dscontents) == int(recipients) {
				// Get error messages
				v.Diagnosis += e + " "
				if strings.HasPrefix(e, startingof["error"][0]) { anotherone[rightindex] = e }

				if v.Rhost != "" { continue }
				for _, r := range startingof["rhost"] {
					// Connected to 192.0.2.225 but sender was rejected.
					// Connected to 192.0.2.112 but my name was rejected.
					// Giving up on 192.0.2.135.
					// remote host 203.138.180.112 said:...
					if cv := moji.Select(e + " ", r, " ", 0); cv != "" { v.Rhost = cv; break }
				}
			}
		}
		if recipients == 0 { return nil }

		for j, _ := range dscontents {
			// Tidy up the error message in e.Diagnosis, Try to detect the bounce reason.
			e := &dscontents[j]
			e.Diagnosis = strings.Join(strings.Fields(e.Diagnosis), " ")

			for r := range commandset {
				// Get the last SMTP command
				if moji.ContainsAny(e.Diagnosis, commandset[r]) { e.Command = r; break }
			}
			if e.Command == "" && strings.Contains(e.Diagnosis, "no SMTP connection got far enough") {
				// Sorry, no SMTP connection got far enough; most progress was RCPT TO response; ...
				e.Command = command.Find(e.Diagnosis)
			}

			if e.Command == eb.CeEHLO || e.Command == eb.CeHELO {
				// HELO | Connected to 192.0.2.135 but my name was rejected.
				e.Reason = eb.ReBLOC

			} else {
				// The error message includes any of patterns defined in the variable avobe
				for _, f := range []string{anotherone[j], e.Diagnosis} {
					// Check that the error message includes any of message patterns or not
					if e.Reason != "" { break    }
					if f == ""        { continue }
					for r := range messagesof {
						// The key name is a bounce reason name
						if moji.ContainsAny(f, messagesof[r]) { e.Reason = r; break }
					}
				}
			}
			if e.Command == "" { e.Command = command.Find(e.Diagnosis) }
		}
		return &siba.RisingUnderway{Digest: dscontents, RFC822: emailparts[1]}
	}
}

