// Copyright (C) 2024-2026 azumakuniyuki and sisimai development team, All rights reserved.
// This software is distributed under The BSD 2-Clause License.
//  _ _               _      ____  ____   
// | | |__   ___  ___| |_   / /\ \/ / /_  
// | | '_ \ / _ \/ __| __| / /  \  / '_ \ 
// | | | | | (_) \__ \ |_ / /   /  \ (_) |
// |_|_| |_|\___/|___/\__/_/   /_/\_\___/ 

package lhost
import "strings"
import "libsisimai.org/sisimai/v5/siba"
import "libsisimai.org/sisimai/v5/address"
import "libsisimai.org/sisimai/v5/rfc1123"
import "libsisimai.org/sisimai/v5/rfc5322"
import "libsisimai.org/sisimai/v5/smtp/command"

func init() {
	// InquireFor[*] decode bounce messages related to or generated by the MTA/ESP of the key name.
	//   Arguments:
	//     - bf (*siba.BeforeFact):  Message entity in progress.
	//   Returns:
	//     - (*siba.RisingUnderway): A structure as a staging data that is processed in message.sift() function.
	InquireFor["X6"] = func(bf *siba.BeforeFact) *siba.RisingUnderway {
		// - Unknown MTA #6
		// - Can anyone identify the MTA that produced the set-of-emails/maildir/bsd/lhost-x6-*.eml files?
		if bf == nil || bf.IsEmpty() == true { return nil }
		if strings.HasPrefix(bf.Headers["subject"][0], "There was an error sending your mail") == false { return nil }

		boundaries := []string{"The attachment contains the original mail headers"}
		startingof := map[string][]string{"message": []string{"We had trouble delivering your message. Full details follow:"}}

		dscontents := make([]siba.DeliveryMatter, 1); v := &dscontents[0]
		emailparts := rfc5322.Part(&bf.Payload, boundaries, false)
		recipients, readcursor := uint8(0), uint8(0)

		for e := range strings.Lines(emailparts[0]) {
			// Read error messages and delivery status lines from the head of the email to the
			// previous line of the beginning of the original message.
			e  = strings.TrimRight(e, "\n\r")
			if readcursor == 0 {
				// Beginning of the bounce message or message/delivery-status part
				if strings.HasPrefix(e, startingof["message"][0]) { readcursor |= HereIsDeliveryStatus }
			}
			if readcursor & HereIsDeliveryStatus == 0 || e == "" { continue }

			// We had trouble delivering your message. Full details follow:
			//
			// Subject: 'Nyaan'
			// Date: 'Thu, 29 Apr 2012 23:34:45 +0000'
			//
			// 1 error(s):
			//
			// SMTP Server <mta2.example.jp> rejected recipient <kijitora@example.jp> 
			//   (Error following RCPT command). It responded as follows: [550 5.1.1 User unknown]
			p1 := strings.Index(e, "The following recipients returned permanent errors: ")
			p2 := strings.Index(e, "SMTP Server <")
			p3 := 0
			if p1 == 0 || p2 == 0 {
				// SMTP Server <mta2.example.jp> rejected recipient <kijitora@example.jp>
				// The following recipients returned permanent errors: neko@example.jp.
				if p1 == 0 { p3 = strings.Index(e, ": ") } else { p3 = strings.LastIndex(e, " <") }
				cv := address.S3S4(e[p3:]); if rfc5322.IsEmailAddress(cv) == false { continue }

				if len(v.Recipient) > 0 { v = siba.NextDeliveryMatter(&dscontents) }
				v.Recipient  = cv
				v.Diagnosis += " " + e
				recipients  += 1

			} else if strings.HasPrefix(e, "Date: ") {
				// Date: 'Thu, 29 Apr 2012 23:34:45 +0000'
				v.Date = strings.Trim(e[6:], "'")
			}
		}
		if recipients == 0 { return nil }

		for j, _ := range dscontents {
			// Tidy up the error message in e.Diagnosis
			e := &dscontents[j]
			e.Command = command.Find(e.Diagnosis)
			e.Rhost   = rfc1123.Find(e.Diagnosis)
		}
		return &siba.RisingUnderway{Digest: dscontents, RFC822: emailparts[1]}
	}
}

