// Copyright (C) 2020,2024-2026 azumakuniyuki and sisimai development team, All rights reserved.
// This software is distributed under The BSD 2-Clause License.
//  _ _               _      __                  _                 _ _ 
// | | |__   ___  ___| |_   / /__  ___ _ __   __| |_ __ ___   __ _(_) |
// | | '_ \ / _ \/ __| __| / / __|/ _ \ '_ \ / _` | '_ ` _ \ / _` | | |
// | | | | | (_) \__ \ |_ / /\__ \  __/ | | | (_| | | | | | | (_| | | |
// |_|_| |_|\___/|___/\__/_/ |___/\___|_| |_|\__,_|_| |_| |_|\__,_|_|_|

package lhost
import "slices"
import "strings"
import "libsisimai.org/sisimai/v5/eb"
import "libsisimai.org/sisimai/v5/siba"
import "libsisimai.org/sisimai/v5/moji"
import "libsisimai.org/sisimai/v5/address"
import "libsisimai.org/sisimai/v5/rfc1894"
import "libsisimai.org/sisimai/v5/rfc5322"
import "libsisimai.org/sisimai/v5/smtp/reply"
import "libsisimai.org/sisimai/v5/smtp/status"
import "libsisimai.org/sisimai/v5/smtp/command"

func init() {
	// InquireFor[*] decode bounce messages related to or generated by the MTA/ESP of the key name.
	//   Arguments:
	//     - bf (*siba.BeforeFact):  Message entity in progress.
	//   Returns:
	//     - (*siba.RisingUnderway): A structure as a staging data that is processed in message.sift() function.
	InquireFor["Sendmail"] = func(bf *siba.BeforeFact) *siba.RisingUnderway {
		// - V8Sendmail: /usr/sbin/sendmail
		// - Sendmail Sentrion Open Source
		// - https://www.proofpoint.com/us/products/email-protection/open-source-email-solution
		if bf == nil || bf.IsEmpty() || len(bf.Headers["x-aol-ip"]) > 0 { return nil } // X-AOL-IP is a header defined in AOL

		switch {
			// Subject: Warning: could not send message for past 4 hours
			// Subject: Returned mail: see transcript for details
			case strings.HasPrefix(bf.Headers["subject"][0], "Warning: "):
			case strings.HasSuffix(bf.Headers["subject"][0], "see transcript for details"):
			default: return nil
		}

		boundaries := [][]byte{[]byte("Content-Type: message/rfc822"), []byte("Content-Type: text/rfc822-headers")}
		startingof := map[string][]string{
			// savemail.c:1040|if (printheader && !putline("   ----- Transcript of session follows -----\n",
			// savemail.c:1041|          mci))
			// savemail.c:1042|  goto writeerr;
			// savemail.c:1360|if (!putline(
			// savemail.c:1361|    sendbody
			// savemail.c:1362|    ? "   ----- Original message follows -----\n"
			// savemail.c:1363|    : "   ----- Message header follows -----\n",
			"message": []string{"   ----- Transcript of session follows -----"},
			"error":   []string{"... while talking to "},
		}
		permessage := map[string]string{}   // Store values of each Per-Message field
		keystrings := make([]string, 0, 4)  // Key list of permessage
		dscontents := make([]siba.DeliveryMatter, 1); v := &dscontents[0]
		emailparts := rfc5322.Part(bf.Payload, boundaries, false)
		readslices := make([]string, 1, 32) // Copy each line for later reference
		esmtpreply := make([]string, 0, 2)  // Reply messages from the remote server on an SMTP session
		anotherset := map[string]string{}   // Another error information
		sessionerr := false                 // Flag, true if it is an SMTP session error
		thecommand := ""                    // An SMTP command name begins with the string ">>>"
		recipients, readcursor := uint8(0), uint8(0)

		j := -1; for e := range strings.Lines(emailparts[0]) {
			// Read error messages and delivery status lines from the head of the email to the
			// previous line of the beginning of the original message.
			j++; e = strings.TrimRight(e, "\n\r")
			readslices = append(readslices, e) // Save the current line for the next loop

			if readcursor == 0 {
				// Beginning of the bounce message or message/delivery-status part
				if strings.HasPrefix(e, startingof["message"][0]) { readcursor |= HereIsDeliveryStatus }
				continue
			}
			if readcursor & HereIsDeliveryStatus == 0 { continue }

			if f := rfc1894.Match(e); f > 0 {
				// "e" matched with any field defined in RFC3464
				o := rfc1894.Field(e); if len(o) == 0 { continue }
				z := rfc1894.FieldTable[o[0]]
				v  = siba.TailDeliveryMatter(dscontents)

				switch o[3] {
				case "addr":
					// Final-Recipient: rfc822; kijitora@example.jp
					// X-Actual-Recipient: rfc822; kijitora@example.co.jp
					if o[0] == "final-recipient" {
						// Final-Recipient: rfc822; kijitora@example.jp
						if len(v.Recipient) > 0 { v = siba.NextDeliveryMatter(&dscontents) }
						v.Recipient = address.Final(o[2])
						recipients += 1

					} else {
						// X-Actual-Recipient: rfc822; kijitora@example.co.jp
						v.Alias = o[2]
					}
				case "code":
					// # Diagnostic-Code: SMTP; 550 5.1.1 <userunknown@example.jp>... User Unknown
					v.Spec = o[1]
					v.Diagnosis = o[2]

				default:
					// Other DSN fields defined in RFC3464
					v.Update(v.AsRFC1894(o[0]), o[2]); if f != 1 { continue }

					// Copy the lower-cased member name of DeliveryMatter{} for "permessage"
					permessage[z] = o[2]
					if slices.Contains(keystrings, z) == false { keystrings = append(keystrings, z) }
				}
			} else {
				// The line does not begin with a DSN field defined in RFC3464
				//
				// ----- Transcript of session follows -----
				// ... while talking to mta.example.org.:
				// >>> DATA
				// <<< 550 Unknown user recipient@example.jp
				// 554 5.0.0 Service unavailable
				if strings.HasPrefix(e, " ") == false {
					// Other error messages which does not start with " "
					if strings.HasPrefix(e, ">>> ") {
						// >>> DATA (Client Command)
						if thecommand == "" { thecommand = command.Find(e) }

					} else if strings.HasPrefix(e, "<<< ") {
						// <<< Response from SMTP Server
						// Whether the response is included in the "estmpreply" or not
						if moji.IsContained(e[4:], esmtpreply) == false { esmtpreply = append(esmtpreply, e[4:]) }

					} else {
						// Detect an SMTP session error or a connection error
						if sessionerr == true { continue }
						if strings.HasPrefix(e, startingof["error"][0]) {
							// ----- Transcript of session follows -----
							// ... while talking to mta.example.org.:
							sessionerr = true
							continue
						}

						if strings.HasPrefix(e, "<") && moji.Aligned(e, []string{"@", ">.", " "}) {
							// <kijitora@example.co.jp>... Deferred: Name server: example.co.jp.: host name lookup failure
							anotherset["recipient"] = moji.Select(e, "<", ">", 0)
							anotherset["diagnosis"] = moji.Select(e + moji.RHS, " ", "", 1)

						} else {
							// ----- Transcript of session follows -----
							// Message could not be delivered for too long
							// Message will be deleted from queue
							if x, y := reply.Find(e, ""), status.Find(e, ""); len(x + y) > 7 {
								// 550 5.1.2 <kijitora@example.org>... Message
								//
								// DBI connect('dbname=...')
								// 554 5.3.0 unknown mailer error 255
								anotherset["status"]     = y
								anotherset["diagnosis"] += " " + e

							} else if moji.HasPrefixAny(e, []string{"Message: ", "Warning: "}) {
								// Message could not be delivered for too long
								// Warning: message still undelivered after 4 hours
								anotherset["diagnosis"] += " " + e
							}
						}
					}
				} else {
					// Get the error message continued from the previous line
					if strings.HasPrefix(e, " ")                            == false { continue }
					if strings.HasPrefix(readslices[j], "Diagnostic-Code:") == false { continue }
					v.Diagnosis += " " + moji.Sweep(e)
				}
			}
		}
		if recipients == 0 { return nil }

		for j, _ := range dscontents {
			// Set default values stored in "permessage" if each value in "dscontents" is empty.
			e := &dscontents[j]
			for _, z := range keystrings {
				// Do not set an empty string into each member of DeliveryMatter{}
				if len(v.Select(z)) > 0 || len(permessage[z]) == 0 { continue }
				e.Update(z, permessage[z])
			}

			switch {
				// Copy alternative error message to e.Diagnosis
				case len(anotherset["diagnosis"]) == 0: 
				case strings.HasPrefix(e.Diagnosis, " "):   e.Diagnosis = anotherset["diagnosis"]
				case moji.ContainsOnlyNumbers(e.Diagnosis): e.Diagnosis = anotherset["diagnosis"]
				case len(e.Diagnosis) == 0:                 e.Diagnosis = anotherset["diagnosis"]
			}

			if len(esmtpreply) > 0 && recipients == 1 {
				// Replace or append the error message in "diagnosis" with the ESMTP Reply Code
				// when the following conditions have matched
				e.Diagnosis = strings.Join(esmtpreply, " ") + " " + e.Diagnosis
			}
			e.Diagnosis = moji.Sweep(e.Diagnosis)
			if e.Command == "" { e.Command = thecommand }
			if e.Command == "" { e.Command = command.Find(e.Diagnosis) }
			if e.Command == "" { if len(esmtpreply) > 0 { e.Command = eb.CeEHLO }}

			// Check alternative status code and override it
			if len(anotherset["status"]) > 0 && status.Test(e.Status) == false { e.Status = anotherset["status"] }

			if strings.HasPrefix(e.Recipient, "@") {
				// There is no local part in the recipient address such as "@mail.example.org"
				// Get the email address from the value of Diagnostic-Code field
				if cv := address.Find(e.Diagnosis); cv[0] != "" { e.Recipient = cv[0] }
			}
		}
		return &siba.RisingUnderway{Digest: dscontents, RFC822: emailparts[1]}
	}
}

