// Copyright (C) 2024-2026 azumakuniyuki and sisimai development team, All rights reserved.
// This software is distributed under The BSD 2-Clause License.
//  _ _               _      ___                     _              _                           
// | | |__   ___  ___| |_   / / \   _ __   __ _  ___| |__   ___    | | __ _ _ __ ___   ___  ___ 
// | | '_ \ / _ \/ __| __| / / _ \ | '_ \ / _` |/ __| '_ \ / _ \_  | |/ _` | '_ ` _ \ / _ \/ __|
// | | | | | (_) \__ \ |_ / / ___ \| |_) | (_| | (__| | | |  __/ |_| | (_| | | | | | |  __/\__ \
// |_|_| |_|\___/|___/\__/_/_/   \_\ .__/ \__,_|\___|_| |_|\___|\___/ \__,_|_| |_| |_|\___||___/
//                                 |_|                                                          

package lhost
import "strings"
import "libsisimai.org/sisimai/v5/siba"
import "libsisimai.org/sisimai/v5/moji"
import "libsisimai.org/sisimai/v5/rfc5322"

func init() {
	// InquireFor[*] decode bounce messages related to or generated by the MTA/ESP of the key name.
	//   Arguments:
	//     - bf (*siba.BeforeFact):  Message entity in progress.
	//   Returns:
	//     - (*siba.RisingUnderway): A structure as a staging data that is processed in message.sift() function.
	InquireFor["ApacheJames"] = func(bf *siba.BeforeFact) *siba.RisingUnderway {
		// - Apache James: https://james.apache.org/
		if bf == nil || bf.IsEmpty() == true { return nil }

		switch {
			// Subject:     [BOUNCE]
			// Message-Id:  JavaMail.
			// Received: from localhost ([127.0.0.1]) by mx.example.org (JAMES SMTP Server 2.3.2) with SMTP ID 220...
			case bf.Headers["subject"][0] == "[BOUNCE]":
			case strings.Contains(bf.Headers["message-id"][0], ".JavaMail."):
			case moji.IsContained("JAMES SMTP Server", bf.Headers["received"]):
			default: return nil
		}

		boundaries := []string{"Content-Type: message/rfc822"}
		startingof := map[string][]string{
			// apache-james-2.3.2/src/java/org/apache/james/transport/mailets/
			//   AbstractNotify.java|124:  out.println("Error message below:");
			//   AbstractNotify.java|128:  out.println("Message details:");
			"message": []string{"Message details:"},
		}
		dscontents := make([]siba.DeliveryMatter, 1); v := &dscontents[0]
		emailparts := rfc5322.Part(&bf.Payload, boundaries, false)
		alternates := [4]string{} // [Envelope-From, Header-From, Date, Subject]
		recipients, readcursor := uint8(0), uint8(0)

		for e := range strings.Lines(emailparts[0]) {
			// Read error messages and delivery status lines from the head of the email to the
			// previous line of the beginning of the original message.
			e  = strings.TrimRight(e, "\n\r")
			if readcursor == 0 {
				// Beginning of the bounce message or message/delivery-status part
				if strings.HasPrefix(e, startingof["message"][0]) {
					// Message details:
					//   Subject: Nyaaan
					readcursor |= HereIsDeliveryStatus
					continue
				}
				if e != "" { v.Diagnosis += e + " " }
				continue
			}
			if readcursor & HereIsDeliveryStatus == 0 || e == "" { continue }

			switch {
				// Message details:
				//   Subject: Nyaaan
				//   Sent date: Thu Apr 29 01:20:50 JST 2015
				//   MAIL FROM: shironeko@example.jp
				//   RCPT TO: kijitora@example.org
				//   From: Neko <shironeko@example.jp>
				//   To: kijitora@example.org
				//   Size (in bytes): 1024
				//   Number of lines: 64
				case strings.HasPrefix(e, "  RCPT TO: "):   //   RCPT TO: kijitora@example.org
					if len(v.Recipient) > 0 { v = siba.NextDeliveryMatter(&dscontents) }
					v.Recipient = e[12:]
					recipients += 1

				case strings.HasPrefix(e, "  Sent date: "): //   Sent date: Thu Apr 29 01:20:50 JST 2015
					v.Date        = e[13:]
					alternates[2] = v.Date

				case strings.HasPrefix(e, "  Subject: "):   alternates[3] = e[11:]
				case strings.HasPrefix(e, "  MAIL FROM: "): alternates[0] = e[13:]
				case strings.HasPrefix(e, "  From: "):      alternates[1] = e[8:]
			}
		}
		if recipients == 0 { return nil }

		if emailparts[1] == "" {
			// The original message is empty
			if alternates[1] != "" { emailparts[1] += "From: " + alternates[1] + "\n" }
			if alternates[2] != "" { emailparts[1] += "Date: " + alternates[2] + "\n" }
		}
		if strings.Contains(emailparts[1], "Return-Path: ") == false {
			// Set the envelope from address as a Return-Path: header
			if alternates[0] != "" { emailparts[1] += "Return-Path: <" + alternates[0] + ">\n" }
		}
		if strings.Contains(emailparts[1], "\nSubject: ") == false {
			// There is no Subject field in the original message
			if alternates[3] != "" { emailparts[1] += "Subject: " + alternates[3] + "\n" }
		}
		return &siba.RisingUnderway{Digest: dscontents, RFC822: emailparts[1]}
	}
}

