// Copyright (C) 2024-2026 azumakuniyuki and sisimai development team, All rights reserved.
// This software is distributed under The BSD 2-Clause License.
//  _ _               _      _______                   _ __  __ _                
// | | |__   ___  ___| |_   / /_   _| __ ___ _ __   __| |  \/  (_) ___ _ __ ___  
// | | '_ \ / _ \/ __| __| / /  | || '__/ _ \ '_ \ / _` | |\/| | |/ __| '__/ _ \ 
// | | | | | (_) \__ \ |_ / /   | || | |  __/ | | | (_| | |  | | | (__| | | (_) |
// |_|_| |_|\___/|___/\__/_/    |_||_|  \___|_| |_|\__,_|_|  |_|_|\___|_|  \___/ 

package lhost
import "strings"
import "libsisimai.org/sisimai/v5/eb"
import "libsisimai.org/sisimai/v5/siba"
import "libsisimai.org/sisimai/v5/moji"
import "libsisimai.org/sisimai/v5/address"
import "libsisimai.org/sisimai/v5/rfc5322"
import "libsisimai.org/sisimai/v5/smtp/command"

func init() {
	// InquireFor[*] decode bounce messages related to or generated by the MTA/ESP of the key name.
	//   Arguments:
	//     - bf (*siba.BeforeFact):  Message entity in progress.
	//   Returns:
	//     - (*siba.RisingUnderway): A structure as a staging data that is processed in message.sift() function.
	InquireFor["TrendMicro"] = func(bf *siba.BeforeFact) *siba.RisingUnderway {
		// - TREND VISION ONE: Email and Collaboration Security
		// - https://www.trendmicro.com/en_us/business/products/email-and-collaboration.html
		// - Formerly known as "Trend Micro InterScan Messaging Security Suite"
		if bf == nil || bf.IsEmpty() == true { return nil }

		switch {
			case strings.HasPrefix(bf.Headers["from"][0], `"InterScan`):
			case strings.Contains(bf.Headers["content-type"][0], "InterScan"):
			case strings.Contains(bf.Payload, " InterScan "):
			default: return nil
		}

		boundaries := []string{"Content-Type: message/rfc822"}
		dscontents := make([]siba.DeliveryMatter, 1); v := &dscontents[0]
		emailparts := rfc5322.Part(&bf.Payload, boundaries, false)
		recipients := uint8(0)

		for e := range strings.Lines(emailparts[0]) {
			// Read error messages and delivery status lines from the head of the email to the
			// previous line of the beginning of the original message.
			e  = strings.TrimRight(e, "\n\r"); if e == "" { continue }

			p1, p2 := strings.Index(e, " <<< "), strings.Index(e, " >>> ")
			if strings.IndexByte(e, '@') > 1 && strings.Index(e, " <") > 1 && 
			   (p1 > 1 || p2 > 1 || strings.Contains(e, "Unable to deliver ")) {
				// Sent <<< RCPT TO:<kijitora@example.co.jp>
				// Received >>> 550 5.1.1 <kijitora@example.co.jp>... user unknown
				// Received >>> 550 5.1.1 unknown user.
				// Unable to deliver message to <kijitora@neko.example.jp>
				// Unable to deliver message to <neko@example.jp> (and other recipients in the same domain).
				p3, p4 := strings.LastIndexByte(e, '<'), strings.LastIndexByte(e, '>')
				cr := address.Find(e[p3:p4 + 1])
				if len(cr) == 0 || rfc5322.IsEmailAddress(cr[0]) == false { continue }

				if len(v.Recipient) > 0 && strings.Contains(cr[0], v.Recipient) == false {
					// There are multiple recipient addresses in the message body.
					v = siba.NextDeliveryMatter(&dscontents)
				}
				if strings.Contains(e, "Unable to deliver ") { v.Diagnosis = e }

				v.Recipient = address.S3S4(cr[0])
				recipients  = uint8(len(dscontents))
			}

			// - Sent <<< RCPT TO:<kijitora@example.co.jp>
			// - Received >>> 550 5.1.1 <kijitora@example.co.jp>... user unknown
			switch {
			case strings.HasPrefix(e, "Sent <<< "):     v.Command   = command.Find(e)
			case strings.HasPrefix(e, "Received >>> "): v.Diagnosis = moji.Select(e + moji.RHS, " >>> ", "", 8)
			default:
				if p1 > 0 || p2 > 0 {
					// Error messages are not written in English
					if strings.Contains(e, " >>> ") { v.Command   = command.Find(e) }
					if strings.Contains(e, " <<< ") { v.Diagnosis = moji.Select(e + moji.RHS, "<<<", "", 3) }
				}
			}
		}
		if recipients == 0 { return nil }

		for j, _ := range dscontents {
			// Tidy up error messages in e.Diagnosis, set the value of e.Reason
			e := &dscontents[j]
			e.Diagnosis = moji.Sweep(e.Diagnosis)
			if strings.Contains(e.Diagnosis, "Unable to deliver") { e.Reason = eb.ReUSER }
		}

		return &siba.RisingUnderway{Digest: dscontents, RFC822: emailparts[1]}
	}
}

