// Copyright (C) 2024-2026 azumakuniyuki and sisimai development team, All rights reserved.
// This software is distributed under The BSD 2-Clause License.
//  _ _               _      _____                   ____  __  __ _____ ____  ____  
// | | |__   ___  ___| |_   / / _ \ _ __   ___ _ __ / ___||  \/  |_   _|  _ \|  _ \ 
// | | '_ \ / _ \/ __| __| / / | | | '_ \ / _ \ '_ \\___ \| |\/| | | | | |_) | | | |
// | | | | | (_) \__ \ |_ / /| |_| | |_) |  __/ | | |___) | |  | | | | |  __/| |_| |
// |_|_| |_|\___/|___/\__/_/  \___/| .__/ \___|_| |_|____/|_|  |_| |_| |_|   |____/ 
//                                 |_|                                              

package lhost
import "strings"
import "libsisimai.org/sisimai/v5/eb"
import "libsisimai.org/sisimai/v5/siba"
import "libsisimai.org/sisimai/v5/moji"
import "libsisimai.org/sisimai/v5/rfc5322"

func init() {
	// InquireFor[*] decode bounce messages related to or generated by the MTA/ESP of the key name.
	//   Arguments:
	//     - bf (*siba.BeforeFact):  Message entity in progress.
	//   Returns:
	//     - (*siba.RisingUnderway): A structure as a staging data that is processed in message.sift() function.
	InquireFor["OpenSMTPD"] = func(bf *siba.BeforeFact) *siba.RisingUnderway {
		// - OpenSMTPD: https://www.opensmtpd.org/
		if bf == nil || bf.IsEmpty() == true { return nil }

		switch {
			// Received: from localhost (localhost [local]);
			//   by localhost (OpenSMTPD) with ESMTPA id 1e2a9eaa;
			//   for <kijitora@example.jp>;
			case strings.Contains(bf.Headers["subject"][0], "Delivery status notification"):
			case strings.Contains(bf.Headers["from"][0], "Mailer Daemon <"):
			case moji.IsContained(" (OpenSMTPD) with ", bf.Headers["received"]):
			default: return nil
		}

		boundaries := []string{"    Below is a copy of the original message:"}
		startingof := map[string][]string{
			// http://www.openbsd.org/cgi-bin/man.cgi?query=smtpd&sektion=8
			// opensmtpd-5.4.2p1/smtpd/
			//   bounce.c/317://define NOTICE_INTRO \
			//   bounce.c/318:    "    Hi!\n\n"    \
			//   bounce.c/319:    "    This is the MAILER-DAEMON, please DO NOT REPLY to this e-mail.\n"
			//   bounce.c/320:
			//   bounce.c/321:const char *notice_error =
			//   bounce.c/322:    "    An error has occurred while attempting to deliver a message for\n"
			//   bounce.c/323:    "    the following list of recipients:\n\n";
			//   bounce.c/324:
			//   bounce.c/325:const char *notice_warning =
			//   bounce.c/326:    "    A message is delayed for more than %s for the following\n"
			//   bounce.c/327:    "    list of recipients:\n\n";
			//   bounce.c/328:
			//   bounce.c/329:const char *notice_warning2 =
			//   bounce.c/330:    "    Please note that this is only a temporary failure report.\n"
			//   bounce.c/331:    "    The message is kept in the queue for up to %s.\n"
			//   bounce.c/332:    "    You DO NOT NEED to re-send the message to these recipients.\n\n";
			//   bounce.c/333:
			//   bounce.c/334:const char *notice_success =
			//   bounce.c/335:    "    Your message was successfully delivered to these recipients.\n\n";
			//   bounce.c/336:
			//   bounce.c/337:const char *notice_relay =
			//   bounce.c/338:    "    Your message was relayed to these recipients.\n\n";
			//   bounce.c/339:
			"message": []string{"    This is the MAILER-DAEMON, please DO NOT REPLY to this"},
		}
		messagesof := map[string][]string{
			// smtpd/queue.c:221|  envelope_set_errormsg(&evp, "Envelope expired");
			// smtpd/mta.c:1013|  relay->failstr = "Could not retrieve credentials";
			eb.ReTIME: []string{"Envelope expired"},
			eb.ReSECU: []string{"Could not retrieve credentials"},
			eb.ReHOST: []string{
				// smtpd/mta.c:976|  relay->failstr = "Invalid domain name";
				// smtpd/mta.c:980|  relay->failstr = "Domain does not exist";
				"Invalid domain name",
				"Domain does not exist",
			},
			eb.ReNETW: []string{
				//  smtpd/mta.c:972|  relay->failstr = "Temporary failure in MX lookup";
				"Address family mismatch on destination MXs",
				"All routes to destination blocked",
				"bad DNS lookup error code",
				"Could not retrieve source address",
				"Loop detected",
				"Network error on destination MXs",
				"No valid route to remote MX",
				"No valid route to destination",
				"Temporary failure in MX lookup",
			},
			eb.Re00MX: []string{
				// smtp/mta.c:1085|  relay->failstr = "Destination seem to reject all mails";
				"Destination seem to reject all mails",
				"No MX found for domain",
				"No MX found for destination",
			},
		}

		dscontents := make([]siba.DeliveryMatter, 1); v := &dscontents[0]
		emailparts := rfc5322.Part(&bf.Payload, boundaries, false)
		recipients, readcursor := uint8(0), uint8(0)

		for e := range strings.Lines(emailparts[0]) {
			// Read error messages and delivery status lines from the head of the email to the
			// previous line of the beginning of the original message.
			e  = strings.TrimRight(e, "\n\r")
			if readcursor == 0 {
				// Beginning of the bounce message or message/delivery-status part
				if strings.HasPrefix(e, startingof["message"][0]) { readcursor |= HereIsDeliveryStatus }
				continue
			}
			if readcursor & HereIsDeliveryStatus == 0 || e == "" { continue }

			//    Hi!
			//
			//    This is the MAILER-DAEMON, please DO NOT REPLY to this e-mail.
			//
			//    An error has occurred while attempting to deliver a message for
			//    the following list of recipients:
			//
			// kijitora@example.jp: 550 5.2.2 <kijitora@example>... Mailbox Full
			//
			//    Below is a copy of the original message:
			if moji.Aligned(e, []string{"@", " "}) {
				// kijitora@example.jp: 550 5.2.2 <kijitora@example.jp>... Mailbox Full
				if len(v.Recipient) > 0 { v = siba.NextDeliveryMatter(&dscontents) }
				v.Recipient = moji.Select(moji.LHS + e, "", ":", 0)
				v.Diagnosis = moji.Select(e + moji.RHS, ": ", "", 0)
				recipients += 1
			}
		}
		if recipients == 0 { return nil }

		for j, _ := range dscontents {
			// Tidy up the error message in e.Diagnosis, Try to detect the bounce reason.
			e := &dscontents[j]
			e.Diagnosis = moji.Sweep(e.Diagnosis)

			for r := range messagesof {
				// The key name is a bounce reason name
				// Try to find an error message including lower-cased string listed in messagesof
				if moji.ContainsAny(e.Diagnosis, messagesof[r]) { e.Reason = r; break }
			}
		}

		return &siba.RisingUnderway{Digest: dscontents, RFC822: emailparts[1]}
	}
}

