// Copyright (C) 2024-2025 azumakuniyuki and sisimai development team, All rights reserved.
// This software is distributed under The BSD 2-Clause License.
//  _ _               _      ___  ______  ____ ___ 
// | | |__   ___  ___| |_   / / |/ /  _ \|  _ \_ _|
// | | '_ \ / _ \/ __| __| / /| ' /| | | | | | | | 
// | | | | | (_) \__ \ |_ / / | . \| |_| | |_| | | 
// |_|_| |_|\___/|___/\__/_/  |_|\_\____/|____/___|

package lhost
import "strings"
import "libsisimai.org/sisimai/sis"
import "libsisimai.org/sisimai/moji"
import "libsisimai.org/sisimai/address"
import "libsisimai.org/sisimai/rfc5322"
import "libsisimai.org/sisimai/smtp/command"

func init() {
	// InquireFor[*] decode bounce messages related to or generated by the MTA/ESP of the key name.
	//   Arguments:
	//     - bf (*sis.BeforeFact):  Message entity in progress
	//   Returns:
	//     - (*sis.RisingUnderway): A structure as a staging data that is processed in message.sift() function
	InquireFor["KDDI"] = func(bf *sis.BeforeFact) *sis.RisingUnderway {
		// - au by KDDI: https://www.au.kddi.com
		if bf == nil || bf.Empty() == true { return nil }

		proceedsto := false
		senderlist := []string{"no-reply@.", ".dion.ne.jp"}
		replyslist := []string{"no-reply@app.auone-net.jp"}
		ISKDDI: for {
			replyto := ""; if len(bf.Headers["reply-to"]) > 0  { replyto = bf.Headers["reply-to"][0] }
			if moji.ContainsAny(bf.Headers["from"][0], senderlist) { proceedsto = true; break ISKDDI }
			if moji.ContainsAny(replyto, replyslist)               { proceedsto = true; break ISKDDI }

			for _, e := range bf.Headers["received"] {
				// Received: from ezweb.ne.jp (nx3oBP05-09.ezweb.ne.jp [59.135.39.233])
				if strings.Contains(e, "ezweb.ne.jp (") { proceedsto = true; break ISKDDI }
				if strings.Contains(e, ".au.com (")     { proceedsto = true; break ISKDDI }
			}
			break
		}
		if proceedsto == false { return nil }

		boundaries := []string{"Content-Type: message/rfc822"}
		startingof := map[string][]string{
			"message": []string{"Your mail sent on:", "Your mail attempted to be delivered on:"},
		}
		messagesof := map[string][]string{
			"mailboxfull": []string{"As their mailbox is full"},
			"norelaying":  []string{"Due to the following SMTP relay error"},
			"hostunknown": []string{"As the remote domain doesnt exist"},
		}

		dscontents := []sis.DeliveryMatter{{}}
		emailparts := rfc5322.Part(&bf.Payload, boundaries, false)
		readcursor := uint8(0)            // Points the current cursor position
		recipients := uint8(0)            // The number of 'Final-Recipient' header
		v          := &(dscontents[len(dscontents) - 1])

		for _, e := range(strings.Split(emailparts[0], "\n")) {
			// Read error messages and delivery status lines from the head of the email to the
			// previous line of the beginning of the original message.
			if readcursor == 0 {
				// Beginning of the bounce message or message/delivery-status part
				if strings.HasPrefix(e, startingof["message"][0]) { readcursor |= Indicators["deliverystatus"] }
			}
			if readcursor & Indicators["deliverystatus"] == 0 || e == "" { continue }

			if strings.Contains(e, " Could not be delivered to: <") {
				// Your mail sent on: Thu, 29 Apr 2010 11:04:47 +0900
				//     Could not be delivered to: <******@**.***.**>
				//     As their mailbox is full.
				if len(v.Recipient) > 0 {
					// There are multiple recipient addresses in the message body.
					dscontents = append(dscontents, sis.DeliveryMatter{})
					v = &(dscontents[len(dscontents) - 1])
				}
				cv := address.S3S4(e[strings.IndexByte(e, '<'):])
				if rfc5322.IsEmailAddress(cv) { v.Recipient = cv; recipients++ }

			} else if strings.Contains(e, "Your mail sent on: ") {
				// Your mail sent on: Thu, 29 Apr 2010 11:04:47 +0900
				v.Date = e[19:]

			} else {
				//     As their mailbox is full.
				if strings.HasPrefix(e, " ") { v.Diagnosis += e + " " }
			}
		}
		if recipients == 0 { return nil }

		for j, _ := range dscontents {
			// Tidy up the error message in e.Diagnosis, Try to detect the bounce reason.
			e := &(dscontents[j])
			e.Diagnosis = moji.Sweep(e.Diagnosis)
			e.Command   = command.Find(e.Diagnosis)

			if len(bf.Headers["x-spasign"]) > 0 && bf.Headers["x-spasign"][0] == "NG" {
				// Content-Type: text/plain; ..., X-SPASIGN: NG (spamghetti, au by KDDI)
				// Filtered recipient returns message that include 'X-SPASIGN' header
				e.Reason = "filtered"

			} else {
				// There is no X-SPASIGN: header in the bounce message
				if e.Command == "RCPT" { e.Reason = "userunkonwn"; continue }

				for r := range messagesof {
					// The key name is a bounce reason name
					// Try to find an error message including lower-cased string listed in messagesof
					if moji.ContainsAny(e.Diagnosis, messagesof[r]) { e.Reason = r; break }
				}
			}
		}
		return &sis.RisingUnderway{Digest: dscontents, RFC822: emailparts[1]}
	}
}

