// Copyright (C) 2024-2025 azumakuniyuki and sisimai development team, All rights reserved.
// This software is distributed under The BSD 2-Clause License.
//  _ _               _      ____  ___ 
// | | |__   ___  ___| |_   / /\ \/ / |
// | | '_ \ / _ \/ __| __| / /  \  /| |
// | | | | | (_) \__ \ |_ / /   /  \| |
// |_|_| |_|\___/|___/\__/_/   /_/\_\_|

package lhost
import "strings"
import "libsisimai.org/sisimai/v5/sis"
import "libsisimai.org/sisimai/v5/moji"
import "libsisimai.org/sisimai/v5/address"
import "libsisimai.org/sisimai/v5/rfc5322"

func init() {
	// InquireFor[*] decode bounce messages related to or generated by the MTA/ESP of the key name.
	//   Arguments:
	//     - bf (*sis.BeforeFact):  Message entity in progress
	//   Returns:
	//     - (*sis.RisingUnderway): A structure as a staging data that is processed in message.sift() function
	InquireFor["X1"] = func(bf *sis.BeforeFact) *sis.RisingUnderway {
		// - Unknown MTA #1
		// - Can anyone identify the MTA that produced the set-of-emails/maildir/bsd/lhost-x1-*.eml files?
		if bf == nil || bf.IsEmpty() == true                                           { return nil }
		if strings.HasPrefix(bf.Headers["subject"][0], "Returned Mail: ")     == false { return nil }
		if strings.HasPrefix(bf.Headers["from"][0], `"Mail Deliver System" `) == false { return nil }

		boundaries := []string{"Received: from "}
		startingof := map[string][]string{"message": []string{"The original message was received at "}}

		dscontents := []sis.DeliveryMatter{{}}
		emailparts := rfc5322.Part(&bf.Payload, boundaries, false)
		readcursor := uint8(0)            // Points the current cursor position
		recipients := uint8(0)            // The number of 'Final-Recipient' header
		v          := &(dscontents[len(dscontents) - 1])

		for _, e := range(strings.Split(emailparts[0], "\n")) {
			// Read error messages and delivery status lines from the head of the email to the
			// previous line of the beginning of the original message.
			if readcursor == 0 {
				// Beginning of the bounce message or message/delivery-status part
				if strings.HasPrefix(e, startingof["message"][0]) { readcursor |= Indicators["deliverystatus"] }
			}
			if readcursor & Indicators["deliverystatus"] == 0 || e == "" { continue }

			// The original message was received at Thu, 29 Apr 2010 23:34:45 +0900 (JST)
			// from shironeko@example.jp
			//
			// ---The following addresses had delivery errors---
			//
			// kijitora@example.co.jp [User unknown]
			if moji.Aligned(e, []string{"@", " [", "]"}) {
				// kijitora@example.co.jp [User unknown]
				if len(v.Recipient) > 0 {
					// There are multiple recipient addresses in the message body.
					dscontents = append(dscontents, sis.DeliveryMatter{})
					v = &(dscontents[len(dscontents) - 1])
				}
				p1 := strings.IndexByte(e, ' ')
				cv := address.S3S4(e[:p1]); if rfc5322.IsEmailAddress(cv) == false { continue }
				v.Recipient  = cv
				v.Diagnosis += " " + e
				recipients  += 1

			} else {
				// The original message was received at Thu, 29 Apr 2010 23:34:45 +0900 (JST) 
				// from shironeko@example.jp
				if strings.HasPrefix(e, "---") && strings.HasSuffix(e, "---") {
					// ---The following addresses had delivery errors---
					e = strings.Trim(e, "---"); e += ":"
					v.Diagnosis += "."
				}
				v.Diagnosis += " " + e
			}
		}
		if recipients == 0 { return nil }

		for j, _ := range dscontents {
			// Tidy up the error message in e.Diagnosis, Pick the date string from the error message.
			e := &(dscontents[j])
			e.Diagnosis = moji.Sweep(e.Diagnosis)

			if e.Date == "" {
				// The original message was received at Thu, 29 Apr 2010 23:34:45 +0900 (JST)
				// from shironeko@example.jp
				e.Date = strings.Trim(moji.Select(e.Diagnosis, " at ", "from", 0), " ")
			}
		}
		return &sis.RisingUnderway{Digest: dscontents, RFC822: emailparts[1]}
	}
}

