// Copyright (C) 2026 azumakuniyuki and sisimai development team, All rights reserved.
// This software is distributed under The BSD 2-Clause License.
//  _ _               _      ______             _            _         _____    _      _                   
// | | |__   ___  ___| |_   / /  _ \  ___ _   _| |_ ___  ___| |__   __|_   _|__| | ___| | _____  _ __ ___  
// | | '_ \ / _ \/ __| __| / /| | | |/ _ \ | | | __/ __|/ __| '_ \ / _ \| |/ _ \ |/ _ \ |/ / _ \| '_ ` _ \ 
// | | | | | (_) \__ \ |_ / / | |_| |  __/ |_| | |_\__ \ (__| | | |  __/| |  __/ |  __/   < (_) | | | | | |
// |_|_| |_|\___/|___/\__/_/  |____/ \___|\__,_|\__|___/\___|_| |_|\___||_|\___|_|\___|_|\_\___/|_| |_| |_|

package lhost
import "strings"
import "libsisimai.org/sisimai/v5/siba"
import "libsisimai.org/sisimai/v5/moji"
import "libsisimai.org/sisimai/v5/rfc5322"

func init() {
	// InquireFor[*] decode bounce messages related to or generated by the MTA/ESP of the key name.
	//   Arguments:
	//     - bf (*siba.BeforeFact):  Message entity in progress.
	//   Returns:
	//     - (*siba.RisingUnderway): A structure as a staging data that is processed in message.sift() function.
	InquireFor["DeutscheTelekom"] = func(bf *siba.BeforeFact) *siba.RisingUnderway {
		// - T-Online: https://www.t-online.de/, @t-online.de, @magenta.de
		// - DeutscheTelekom: https://www.telekom.com/
		//   - Based on the bounce format of Smail 3, the original design model for Exim
		//   - Tailored for Deutsche Telekom's internal Smail 3 fork with custom banners
		//   - Module name follows the infrastructure owner for cross-language compatibility
		// - Smail 3: http://www.weird.com/~woods/projects/smail.html
		if bf == nil || bf.IsEmpty() == true { return nil }

		switch {
			// smail-3.2.0.108/src/
			//  notify.c:1052|(void) fprintf(f, "Subject: mail failed, %s\nReference: <%s@%s>\n\n",
			//  notify.c:1053|       subject_to, message_id, primary_name);
			case strings.HasPrefix(bf.Headers["subject"][0], "mail failed, "):
			case moji.ContainsAny(bf.Payload, BannerDTAG):
			default: return nil
		}

		boundaries := []string{BannerDTAG[3], BannerDTAG[2]} /* [3] is the first */
		startingof := map[string][]string{"message": []string{BannerDTAG[1]}}
		dscontents := make([]siba.DeliveryMatter, 1); v := &dscontents[0]
		emailparts := rfc5322.Part(&bf.Payload, boundaries, false)
		messagelog := ""
		recipients, readcursor := uint8(0), uint8(0)

		for e := range strings.Lines(emailparts[0]) {
			// Read error messages and delivery status lines from the head of the email to the
			// previous line of the beginning of the original message.
			e  = strings.TrimRight(e, "\n\r")
			if readcursor == 0 {
				// Beginning of the bounce message or message/delivery-status part
				if strings.HasPrefix(e, startingof["message"][0]) {
					// |------------------------- Failed addresses follow: ---------------------|
					readcursor |= HereIsDeliveryStatus

				} else {
					// |------------------------- Message log follows: -------------------------|
					// The line above may appears only in smail.
					if e != "" && strings.HasPrefix(e, BannerDTAG[0]) == false {
						// smail-3.2.0.108/src/
						//   models.c:787| if (deliver == NULL && defer == NULL) {
						//   models.c:788| write_log(WRITE_LOG_MLOG, "no valid recipients were found for this message");
						//   models.c:789| return_to_sender = TRUE;
						//   models.c:879| }
						messagelog += e + " "
					}
				}
				continue
			}
			if readcursor & HereIsDeliveryStatus == 0 || e == "" { continue }

			// |------------------------- Failed addresses follow: ---------------------|
			//  <example@t-online.de>
			//    552 5.2.2 <example@t-online.de> Quota exceeded (mailbox for user is full)
			//
			// |------------------------- Message header follows: ----------------------|
			// Received: from mail.fragdenstaat.de ([94.130.55.89]) by mailin41.mgt.mul.t-online.de.example.com
			//  with (TLSv1.3:TLS_AES_256_GCM_SHA384 encrypted)
			// ...
			if strings.HasPrefix(e, " <") && strings.HasSuffix(e, ">") && strings.Count(e, " ") == 1 {
				// Deutsche Telekom: The recipient address is enclosed in angle brackets.
				// |------------------------- Failed addresses follow: ---------------------|
				//  <example@t-online.de>
				if len(v.Recipient) > 0 { v = siba.NextDeliveryMatter(&dscontents) }
				v.Recipient = moji.Select(moji.LHS + e, " <", ">", 1)
				recipients += 1

			} else if moji.Aligned(e, []string{" ", "@", ".", " ... "}) {
				// Smail 3:
				//   - The recipient address is not enclosed in angle brackets.
				//   - Error message begins with " ... failed:"
				// smail-3.2.0.108/src/
				//   notify.c:845| if (cur->error) {
				//   notify.c:846| (void) fprintf(f, " %s ... failed: %s\n",
				//   notify.c:847|            cur->in_addr ? cur->in_addr : "(unknown)",
				//   notify.c:848|            cur->error->message);
				//   notify.c:849| }
				// |------------------------- Failed addresses follow: ---------------------|
				//  kijitora@neko.nyaan.example.com ... unknown host
				if len(v.Recipient) > 0 { v = siba.NextDeliveryMatter(&dscontents) }
				v.Recipient = moji.Select(moji.LHS + e, " ", " ... ", 1)
				v.Diagnosis = messagelog + " " + e
				recipients += 1

			} else {
				//    552 5.2.2 <example@t-online.de> Quota exceeded (mailbox for user is full)
				v.Diagnosis = e
			}
		}
		if recipients == 0 { return nil }
		return &siba.RisingUnderway{Digest: dscontents, RFC822: emailparts[1]}
	}
}

