// Copyright (C) 2024-2025 azumakuniyuki and sisimai development team, All rights reserved.
// This software is distributed under The BSD 2-Clause License.
//  _ _               _      ___  ______  ____ ___ 
// | | |__   ___  ___| |_   / / |/ /  _ \|  _ \_ _|
// | | '_ \ / _ \/ __| __| / /| ' /| | | | | | | | 
// | | | | | (_) \__ \ |_ / / | . \| |_| | |_| | | 
// |_|_| |_|\___/|___/\__/_/  |_|\_\____/|____/___|

package lhost
import "strings"
import "libsisimai.org/sisimai/v5/eb"
import "libsisimai.org/sisimai/v5/siba"
import "libsisimai.org/sisimai/v5/moji"
import "libsisimai.org/sisimai/v5/rfc5322"
import "libsisimai.org/sisimai/v5/smtp/command"

func init() {
	// InquireFor[*] decode bounce messages related to or generated by the MTA/ESP of the key name.
	//   Arguments:
	//     - bf (*siba.BeforeFact):  Message entity in progress.
	//   Returns:
	//     - (*siba.RisingUnderway): A structure as a staging data that is processed in message.sift() function.
	InquireFor["KDDI"] = func(bf *siba.BeforeFact) *siba.RisingUnderway {
		// - au by KDDI: https://www.au.kddi.com
		if bf == nil || bf.IsEmpty() == true { return nil }

		senderlist := []string{"no-reply@.", ".dion.ne.jp"}
		replyaddrs := []string{"no-reply@app.auone-net.jp"}
		replyingto := ""; if len(bf.Headers["reply-to"]) > 0 { replyingto = bf.Headers["reply-to"][0] }

		switch {
			// Received: from ezweb.ne.jp (nx3oBP05-09.ezweb.ne.jp [59.135.39.233])
			case moji.ContainsAny(bf.Headers["from"][0], senderlist):
			case moji.ContainsAny(replyingto, replyaddrs):
			case moji.IsContained("ezweb.ne.jp (", bf.Headers["received"]):
			case moji.IsContained(".au.com (",     bf.Headers["received"]):
			default: return nil
		}

		boundaries := []string{"Content-Type: message/rfc822"}
		startingof := map[string][]string{
			"message": []string{"Your mail sent on:", "Your mail attempted to be delivered on:"},
		}
		messagesof := map[string][]string{
			eb.ReFULL: []string{"As their mailbox is full"},
			eb.ReRELA: []string{"Due to the following SMTP relay error"},
			eb.ReHOST: []string{"As the remote domain doesnt exist"},
		}

		dscontents := make([]siba.DeliveryMatter, 1); v := &dscontents[0]
		emailparts := rfc5322.Part(&bf.Payload, boundaries, false)
		recipients, readcursor := uint8(0), uint8(0)

		for e := range strings.Lines(emailparts[0]) {
			// Read error messages and delivery status lines from the head of the email to the
			// previous line of the beginning of the original message.
			e  = strings.TrimRight(e, "\n\r")
			if readcursor == 0 {
				// Beginning of the bounce message or message/delivery-status part
				if strings.HasPrefix(e, startingof["message"][0]) { readcursor |= HereIsDeliveryStatus }
			}
			if readcursor & HereIsDeliveryStatus == 0 || e == "" { continue }

			if strings.Contains(e, " Could not be delivered to: <") {
				// Your mail sent on: Thu, 29 Apr 2010 11:04:47 +0900
				//     Could not be delivered to: <******@**.***.**>
				//     As their mailbox is full.
				if len(v.Recipient) > 0 { v = siba.NextDeliveryMatter(&dscontents) }
				if cv := moji.Select(e, ": <", ">", 16); rfc5322.IsEmailAddress(cv) { v.Recipient = cv; recipients++ }

			} else if strings.Contains(e, "Your mail sent on: ") {
				// Your mail sent on: Thu, 29 Apr 2010 11:04:47 +0900
				v.Date = e[19:]

			} else {
				//     As their mailbox is full.
				if strings.HasPrefix(e, " ") { v.Diagnosis += e + " " }
			}
		}
		if recipients == 0 { return nil }

		for j, _ := range dscontents {
			// Tidy up the error message in e.Diagnosis, Try to detect the bounce reason.
			e := &dscontents[j]
			e.Diagnosis = moji.Sweep(e.Diagnosis)
			e.Command   = command.Find(e.Diagnosis)

			if len(bf.Headers["x-spasign"]) > 0 && bf.Headers["x-spasign"][0] == "NG" {
				// Content-Type: text/plain; ..., X-SPASIGN: NG (spamghetti, au by KDDI)
				// Filtered recipient returns message that include 'X-SPASIGN' header
				e.Reason = eb.ReFILT

			} else {
				// There is no X-SPASIGN: header in the bounce message
				if e.Command == eb.CeRCPT { e.Reason = eb.ReUSER; continue }

				for r := range messagesof {
					// The key name is a bounce reason name
					// Try to find an error message including lower-cased string listed in messagesof
					if moji.ContainsAny(e.Diagnosis, messagesof[r]) { e.Reason = r; break }
				}
			}
		}
		return &siba.RisingUnderway{Digest: dscontents, RFC822: emailparts[1]}
	}
}

