// Copyright (C) 2024-2025 azumakuniyuki and sisimai development team, All rights reserved.
// This software is distributed under The BSD 2-Clause License.
//  _ _               _      _____       _            ____                  __  __ ____ ____  
// | | |__   ___  ___| |_   / /_ _|_ __ | |_ ___ _ __/ ___|  ___ __ _ _ __ |  \/  / ___/ ___| 
// | | '_ \ / _ \/ __| __| / / | || '_ \| __/ _ \ '__\___ \ / __/ _` | '_ \| |\/| \___ \___ \ 
// | | | | | (_) \__ \ |_ / /  | || | | | ||  __/ |   ___) | (_| (_| | | | | |  | |___) |__) |
// |_|_| |_|\___/|___/\__/_/  |___|_| |_|\__\___|_|  |____/ \___\__,_|_| |_|_|  |_|____/____/ 

package lhost
import "strings"
import "libsisimai.org/sisimai/v5/sis"
import "libsisimai.org/sisimai/v5/moji"
import "libsisimai.org/sisimai/v5/address"
import "libsisimai.org/sisimai/v5/rfc5322"
import "libsisimai.org/sisimai/v5/smtp/command"

func init() {
	// InquireFor[*] decode bounce messages related to or generated by the MTA/ESP of the key name.
	//   Arguments:
	//     - bf (*sis.BeforeFact):  Message entity in progress
	//   Returns:
	//     - (*sis.RisingUnderway): A structure as a staging data that is processed in message.sift() function
	InquireFor["InterScanMSS"] = func(bf *sis.BeforeFact) *sis.RisingUnderway {
		// - Trend Micro InterScan Messaging Security Suite
		// - https://www.trendmicro.com/en_us/business/products/user-protection/sps/email-and-collaboration/interscan-messaging.html
		if bf == nil || bf.IsEmpty() == true { return nil }

		proceedsto := false; for {
			if strings.HasPrefix(bf.Headers["from"][0], `"InterScan`)       { proceedsto = true; break }
			if strings.Contains(bf.Headers["content-type"][0], "InterScan") { proceedsto = true; break }
			if strings.Contains(bf.Payload, " InterScan ")                  { proceedsto = true; break }
			break
		}
		if proceedsto == false { return nil }

		boundaries := []string{"Content-Type: message/rfc822"}
		dscontents := make([]sis.DeliveryMatter, 1); v := &dscontents[0]
		emailparts := rfc5322.Part(&bf.Payload, boundaries, false)
		recipients := uint8(0)            // The number of 'Final-Recipient' header

		for _, e := range(strings.Split(emailparts[0], "\n")) {
			// Read error messages and delivery status lines from the head of the email to the
			// previous line of the beginning of the original message.
			if e == "" { continue }

			p1 := strings.Index(e, " <<< ") // Sent <<< ...
			p2 := strings.Index(e, " >>> ") // Received >>> ...
			if strings.IndexByte(e, '@') > 1 && strings.Index(e, " <") > 1 && 
			   (p1 > 1 || p2 > 1 || strings.Contains(e, "Unable to deliver ")) {
				// Sent <<< RCPT TO:<kijitora@example.co.jp>
				// Received >>> 550 5.1.1 <kijitora@example.co.jp>... user unknown
				// Received >>> 550 5.1.1 unknown user.
				// Unable to deliver message to <kijitora@neko.example.jp>
				// Unable to deliver message to <neko@example.jp> (and other recipients in the same domain).
				p3 := strings.LastIndexByte(e, '<')
				p4 := strings.LastIndexByte(e, '>')
				cr := address.Find(e[p3:p4 + 1])
				if len(cr) == 0 || rfc5322.IsEmailAddress(cr[0]) == false { continue }

				if len(v.Recipient) > 0 && strings.Contains(cr[0], v.Recipient) == false {
					// There are multiple recipient addresses in the message body.
					v = sis.NextDeliveryMatter(&dscontents)
				}
				if strings.Contains(e, "Unable to deliver ") { v.Diagnosis = e }

				v.Recipient = address.S3S4(cr[0])
				recipients  = uint8(len(dscontents))
			}

			if strings.HasPrefix(e, "Sent <<< ") {
				// Sent <<< RCPT TO:<kijitora@example.co.jp>
				v.Command = command.Find(e)

			} else if strings.HasPrefix(e, "Received >>> ") {
				// Received >>> 550 5.1.1 <kijitora@example.co.jp>... user unknown
				v.Diagnosis = e[strings.Index(e, " >>> ") + 4:]

			} else if p1 > 0 || p2 > 0 {
				// Error messages are not written in English
				if strings.Contains(e, " >>> ")             { v.Command = command.Find(e) }
				if p3 := strings.Index(e, " <<< "); p3 > -1 { v.Diagnosis = e[p3 + 4:]    }
			}
		}
		if recipients == 0 { return nil }

		for j, _ := range dscontents {
			// Tidy up error messages in e.Diagnosis, set the value of e.Reason
			e := &dscontents[j]
			e.Diagnosis = moji.Sweep(e.Diagnosis)
			if strings.Contains(e.Diagnosis, "Unable to deliver") { e.Reason = "userunknown" }
		}

		return &sis.RisingUnderway{Digest: dscontents, RFC822: emailparts[1]}
	}
}

