// Copyright (C) 20242-2026 azumakuniyuki and sisimai development team, All rights reserved.
// This software is distributed under The BSD 2-Clause License.
//  _ _               _      ____  __                           _             ____                           
// | | |__   ___  ___| |_   / /  \/  | ___  ___ ___  __ _  __ _(_)_ __   __ _/ ___|  ___ _ ____   _____ _ __ 
// | | '_ \ / _ \/ __| __| / /| |\/| |/ _ \/ __/ __|/ _` |/ _` | | '_ \ / _` \___ \ / _ \ '__\ \ / / _ \ '__|
// | | | | | (_) \__ \ |_ / / | |  | |  __/\__ \__ \ (_| | (_| | | | | | (_| |___) |  __/ |   \ V /  __/ |   
// |_|_| |_|\___/|___/\__/_/  |_|  |_|\___||___/___/\__,_|\__, |_|_| |_|\__, |____/ \___|_|    \_/ \___|_|   
//                                                        |___/         |___/                                

package lhost
import "strings"
import "libsisimai.org/sisimai/v5/siba"
import "libsisimai.org/sisimai/v5/moji"
import "libsisimai.org/sisimai/v5/rfc791"
import "libsisimai.org/sisimai/v5/rfc1894"
import "libsisimai.org/sisimai/v5/rfc5322"
import "libsisimai.org/sisimai/v5/smtp/reply"
import "libsisimai.org/sisimai/v5/smtp/status"

func init() {
	// InquireFor[*] decode bounce messages related to or generated by the MTA/ESP of the key name.
	//   Arguments:
	//     - bf (*siba.BeforeFact):  Message entity in progress.
	//   Returns:
	//     - (*siba.RisingUnderway): A structure as a staging data that is processed in message.sift() function.
	InquireFor["MessagingServer"] = func(bf *siba.BeforeFact) *siba.RisingUnderway {
		// - https://docs.oracle.com/en/industries/communications/messaging-server/index.html
		if bf == nil || bf.IsEmpty() == true { return nil }

		switch {
			case strings.Contains(bf.Headers["content-type"][0], "Boundary_(ID_"):
			case strings.HasPrefix(bf.Headers["subject"][0], "Delivery Notification: "):
			default: return nil
		}

		boundaries := []string{"Content-Type: message/rfc822", "\nReturn-Path: "}
		startingof := map[string][]string{
			"message": []string{"This report relates to a message you sent with the following header fields:"},
		}
		envelopeto := [][]string{[]string{"  Recipient address: ", "@", "."}, []string{"  Original address: ",  "@", "."}}

		dscontents := make([]siba.DeliveryMatter, 1); v := &dscontents[0]
		emailparts := rfc5322.Part(&bf.Payload, boundaries, false)
		recipients, readcursor := uint8(0), uint8(0)

		for e := range strings.Lines(emailparts[0]) {
			// Read error messages and delivery status lines from the head of the email to the
			// previous line of the beginning of the original message.
			e  = strings.TrimRight(e, "\n\r")
			if readcursor == 0 {
				// Beginning of the bounce message or message/delivery-status part
				if strings.HasPrefix(e, startingof["message"][0]) { readcursor |= HereIsDeliveryStatus }
				continue
			}
			if readcursor & HereIsDeliveryStatus == 0 || e == "" { continue }

			// --Boundary_(ID_0000000000000000000000)
			// Content-type: text/plain; charset=us-ascii
			// Content-language: en-US
			//
			// This report relates to a message you sent with the following header fields:
			//
			//   Message-id: <CD8C6134-C312-41D5-B083-366F7FA1D752@me.example.com>
			//   Date: Fri, 21 Nov 2014 23:34:45 +0900
			//   From: Shironeko <shironeko@me.example.com>
			//   To: kijitora@example.jp
			//   Subject: Nyaaaaaaaaaaaaaaaaaaaaaan
			//
			// Your message cannot be delivered to the following recipients:
			//
			//   Recipient address: kijitora@example.jp
			//   Reason: Remote SMTP server has rejected address
			//   Diagnostic code: smtp;550 5.1.1 <kijitora@example.jp>... User Unknown
			//   Remote system: dns;mx.example.jp (TCP|17.111.174.67|47323|192.0.2.225|25) (6jo.example.jp ESMTP SENDMAIL-VM)
			if moji.AlignedAny(e, envelopeto) {
				//   Recipient address: @smtp.example.net:kijitora@server
				//   Original address: kijitora@example.jp
				cv := moji.Select(e + moji.RHS, ": ", "", 16)
				if rfc5322.IsEmailAddress(cv) == false { continue }
				if len(v.Recipient) > 0 && cv != v.Recipient { v = siba.NextDeliveryMatter(&dscontents) }

				v.Recipient = cv
				recipients += 1

			} else if strings.HasPrefix(e, "  Date: ") {
				//   Date: Fri, 21 Nov 2014 23:34:45 +0900
				v.Date = moji.Select(e + moji.RHS, "Date: ", "", 1)

			} else if strings.HasPrefix(e, "  Reason: ") {
				//   Reason: Remote SMTP server has rejected address
				v.Date = moji.Select(e + moji.RHS, " Reason: ", "", 1)

			} else if strings.HasPrefix(e, "  Diagnostic code: ") {
				//   Diagnostic code: smtp;550 5.1.1 <kijitora@example.jp>... User Unknown
				e  = strings.Replace(strings.Trim(e, " "), "Diagnostic code:", "Diagnostic-Code:", 1)
				f := rfc1894.Field(e); if len(f) == 0 { continue }
				v.Spec       = f[1]
				v.ReplyCode  = reply.Find(f[2], "")
				v.Status     = status.Find(f[2], v.ReplyCode)
				v.Diagnosis += " " + f[2]

			} else if strings.HasPrefix(e, "  Remote system: ") {
				//   Remote system: dns;mx.example.jp (TCP|17.111.174.67|47323|192.0.2.225|25)
				//     (6jo.example.jp ESMTP SENDMAIL-VM)
				if v.Rhost = moji.Select(e, ";", " (", 0); v.Rhost == "" { continue }
				if cv := strings.Split(moji.Select(e, " (", ")", 0), "|"); len(cv) == 5 {
					// (TCP|17.111.174.67|47323|192.0.2.225|25)
					if cv[0] != "TCP" || strings.IndexByte(v.Rhost, '.') > 0 { continue }
					if rfc791.IsIPv4Address(cv[1]) { v.Lhost = cv[1] }
					if rfc791.IsIPv4Address(cv[3]) { v.Rhost = cv[3] }
				}
			} else {
				// Original-envelope-id: 0NFC009FLKOUVMA0@mr21p30im-asmtp004.me.com
				// Reporting-MTA: dns;mr21p30im-asmtp004.me.com (tcp-daemon)
				// Arrival-date: Thu, 29 Apr 2014 23:34:45 +0000 (GMT)
				//
				// Original-recipient: rfc822;kijitora@example.jp
				// Final-recipient: rfc822;kijitora@example.jp
				// Action: failed
				// Status: 5.1.1 (Remote SMTP server has rejected address)
				// Remote-MTA: dns;mx.example.jp (TCP|17.111.174.67|47323|192.0.2.225|25)
				//  (6jo.example.jp ESMTP SENDMAIL-VM)
				// Diagnostic-code: smtp;550 5.1.1 <kijitora@example.jp>... User Unknown
				switch {
				case strings.HasPrefix(e, "Status: "):
					// Status: 5.1.1 (Remote SMTP server has rejected address)
					if v.Status    == "" { v.Status = status.Find(e, v.ReplyCode)    }
					if v.Diagnosis == "" { v.Diagnosis = moji.Select(e, "(", ")", 1) }

				case strings.HasPrefix(e, "Arrival-Date: "):
					// Arrival-date: Thu, 29 Apr 2014 23:34:45 +0000 (GMT)
					if v.Date == "" { v.Date = moji.Select(e + moji.RHS, "-Date: ", "", 1) }

				case strings.HasPrefix(e, "Reporting-MTA: "):
					// Reporting-MTA: dns;mr21p30im-asmtp004.me.com (tcp-daemon)
					if strings.IndexByte(v.Lhost, '.') > 0 { continue        }
					if cv := rfc1894.Field(e); len(cv) > 0 { v.Lhost = cv[2] }
				}
			}
		}
		if recipients == 0 { return nil }
		return &siba.RisingUnderway{Digest: dscontents, RFC822: emailparts[1]}
	}
}

