// Copyright (C) 2024-2026 azumakuniyuki and sisimai development team, All rights reserved.
// This software is distributed under The BSD 2-Clause License.
//  _ _               _      ___        _   _           _                 _            
// | | |__   ___  ___| |_   / / \   ___| |_(_)_   _____| |__  _   _ _ __ | |_ ___ _ __ 
// | | '_ \ / _ \/ __| __| / / _ \ / __| __| \ \ / / _ \ '_ \| | | | '_ \| __/ _ \ '__|
// | | | | | (_) \__ \ |_ / / ___ \ (__| |_| |\ V /  __/ | | | |_| | | | | ||  __/ |   
// |_|_| |_|\___/|___/\__/_/_/   \_\___|\__|_| \_/ \___|_| |_|\__,_|_| |_|\__\___|_|   

package lhost
import "strings"
import "libsisimai.org/sisimai/v5/siba"
import "libsisimai.org/sisimai/v5/moji"
import "libsisimai.org/sisimai/v5/address"
import "libsisimai.org/sisimai/v5/rfc5322"

func init() {
	// InquireFor[*] decode bounce messages related to or generated by the MTA/ESP of the key name.
	//   Arguments:
	//     - bf (*siba.BeforeFact):  Message entity in progress.
	//   Returns:
	//     - (*siba.RisingUnderway): A structure as a staging data that is processed in message.sift() function.
	InquireFor["Activehunter"] = func(bf *siba.BeforeFact) *siba.RisingUnderway {
		// - QUALITIA Active!hunter: https://www.qualitia.com/jp/product/ah/
		if bf == nil || bf.IsEmpty() == true || len(bf.Headers["x-ahmailid"]) == 0 { return nil }

		boundaries := [][]byte{[]byte("Content-Type: message/rfc822")}
		startingof := map[string][]string{
			"message": []string{"  ----- The following addresses had permanent fatal errors -----"},
		}
		dscontents := make([]siba.DeliveryMatter, 1); v := &dscontents[0]
		emailparts := rfc5322.Part(bf.Payload, boundaries, false)
		recipients, readcursor := uint8(0), uint8(0)

		for e := range strings.Lines(emailparts[0]) {
			// Read error messages and delivery status lines from the head of the email to the
			// previous line of the beginning of the original message.
			if readcursor == 0 {
				// Beginning of the bounce message or message/delivery-status part
				if strings.HasPrefix(e, startingof["message"][0]) { readcursor |= HereIsDeliveryStatus }
				continue
			}
			if readcursor & HereIsDeliveryStatus == 0 || e == "" { continue }

			//  ----- The following addresses had permanent fatal errors -----
			//
			// >>> kijitora@example.org <kijitora@example.org>
			//
			//  ----- Transcript of session follows -----
			// 550 sorry, no mailbox here by that name (#5.1.1 - chkusr)
			if strings.HasPrefix(e, ">>> ") && strings.IndexByte(e, '@') > 0 {
				// >>> kijitora@example.org <kijitora@example.org>
				if len(v.Recipient) > 0 { v = siba.NextDeliveryMatter(&dscontents) }

				v.Recipient = address.S3S4(e[5:])
				recipients += 1

			} else {
				//  ----- Transcript of session follows -----
				// 550 sorry, no mailbox here by that name (#5.1.1 - chkusr)
				if cr := []rune(e[0:1]); cr[0] < 48 || cr[0] > 122 { continue } // 48 = '0', 122 = 'z'
				if v.Diagnosis == "" { v.Diagnosis = e }
			}
		}
		if recipients == 0 { return nil }

		for j, _ := range dscontents { 
			// Remove leading or/and trailing spaces, redandant spaces from the error messaage
			e := &dscontents[j]
			e.Diagnosis = moji.Sweep(e.Diagnosis)
		}
		return &siba.RisingUnderway{Digest: dscontents, RFC822: emailparts[1]}
	}
}

