// Copyright (C) 2024-2026 azumakuniyuki and sisimai development team, All rights reserved.
// This software is distributed under The BSD 2-Clause License.
//  _ _               _      _______      _           
// | | |__   ___  ___| |_   / / ____|_  _(_)_ __ ___  
// | | '_ \ / _ \/ __| __| / /|  _| \ \/ / | '_ ` _ \ 
// | | | | | (_) \__ \ |_ / / | |___ >  <| | | | | | |
// |_|_| |_|\___/|___/\__/_/  |_____/_/\_\_|_| |_| |_|

package lhost
import "strings"
import "libsisimai.org/sisimai/v5/eb"
import "libsisimai.org/sisimai/v5/siba"
import "libsisimai.org/sisimai/v5/moji"
import "libsisimai.org/sisimai/v5/reason"
import "libsisimai.org/sisimai/v5/address"
import "libsisimai.org/sisimai/v5/rfc1123"
import "libsisimai.org/sisimai/v5/rfc1894"
import "libsisimai.org/sisimai/v5/rfc2045"
import "libsisimai.org/sisimai/v5/rfc5322"
import "libsisimai.org/sisimai/v5/smtp/reply"
import "libsisimai.org/sisimai/v5/smtp/status"
import "libsisimai.org/sisimai/v5/smtp/command"
import "libsisimai.org/sisimai/v5/smtp/failure"

func init() {
	// InquireFor[*] decode bounce messages related to or generated by the MTA/ESP of the key name.
	//   Arguments:
	//     - bf (*siba.BeforeFact):  Message entity in progress.
	//   Returns:
	//     - (*siba.RisingUnderway): A structure as a staging data that is processed in message.sift() function.
	InquireFor["Exim"] = func(bf *siba.BeforeFact) *siba.RisingUnderway {
		// - Exim Internet Mailer: https://www.exim.org/
		if bf == nil || bf.IsEmpty() == true { return nil }

		// X-Failed-Recipients: kijitora@example.ed.jp
		thirdparty := false
		proceedsto := uint8(0)
		messageidv := bf.Headers["message-id"][0]
		emailtitle := []string{
			// Subject: Mail delivery failed: returning message to sender
			// Subject: Mail delivery failed
			// Subject: Message frozen
			"Delivery Status Notification",
			"Mail delivery failed",
			"Mail failure",
			"Message frozen",
			"Warning: message ",
			"error(s) in forwarding or filtering",
		}
		if strings.Contains(bf.Headers["from"][0], "Mail Delivery System") { proceedsto++ }
		if moji.ContainsAny(bf.Headers["subject"][0], emailtitle) == true  { proceedsto++ }
		for messageidv != "" {
			// Message-Id: <E1P1YNN-0003AD-Ga@example.org>
			if strings.IndexByte(messageidv, '<') !=  0 { break }
			if strings.IndexByte(messageidv, '-') !=  8 { break }
			if strings.IndexByte(messageidv, '@') != 18 { break }
			proceedsto++; break
		}
		switch {
			// Exim clones of the third Parties
			// 1. McAfee Saas (Formerly MXLogic)
			case len(bf.Headers["x-mx-bounce"])    > 0: thirdparty = true
			case len(bf.Headers["x-mxl-hash"])     > 0: thirdparty = true
			case len(bf.Headers["x-mxl-notehash"]) > 0: thirdparty = true
			case strings.Contains(messageidv, "<mxl~"): thirdparty = true
		}
		if proceedsto < 2 && thirdparty == false { return nil }

		boundaries := []string{
			// deliver.c:6423|          if (bounce_return_body) fprintf(f,
			// deliver.c:6424|"------ This is a copy of the message, including all the headers. ------\n");
			// deliver.c:6425|          else fprintf(f,
			// deliver.c:6426|"------ This is a copy of the message's headers. ------\n");
			"------ This is a copy of the message, including all the headers. ------",
			"Content-Type: message/rfc822",
			"Included is a copy of the message header:\n-----------------------------------------", // MXLogic
		}
		startingof := map[string][]string{
			// Error text strings which are defined in exim/src/deliver.c
			//
			// deliver.c:6292| fprintf(f,
			// deliver.c:6293|"This message was created automatically by mail delivery software.\n");
			// deliver.c:6294|        if (to_sender)
			// deliver.c:6295|          {
			// deliver.c:6296|          fprintf(f,
			// deliver.c:6297|"\nA message that you sent could not be delivered to one or more of its\n"
			// deliver.c:6298|"recipients. This is a permanent error. The following address(es) failed:\n");
			// deliver.c:6299|          }
			// deliver.c:6300|        else
			// deliver.c:6301|          {
			// deliver.c:6302|          fprintf(f,
			// deliver.c:6303|"\nA message sent by\n\n  <%s>\n\n"
			// deliver.c:6304|"could not be delivered to one or more of its recipients. The following\n"
			// deliver.c:6305|"address(es) failed:\n", sender_address);
			// deliver.c:6306|          }
			"alias":          []string{" an undisclosed address"},
			"command":        []string{"SMTP error from remote ", "LMTP error after "},
			"deliverystatus": []string{"Content-Type: message/delivery-status"},
			"frozen":         []string{" has been frozen", " was frozen on arrival"},
			"message":        []string{
				"This message was created automatically by mail delivery software.",
				"A message that you sent was rejected by the local scannning code",
				"A message that you sent contained one or more recipient addresses ",
				"A message that you sent could not be delivered to all of its recipients",
				" has been frozen",
				" was frozen on arrival",
				" router encountered the following error(s):",
			},
		}
		messagesof := map[string][]string{
			// find exim/ -type f -exec grep 'message = US' {} /dev/null \;
			// parser.c:666| *errorptr = string_sprintf("%s (expected word or \"<\")", *errorptr);
			// parser.c:701| if(bracket_count++ > 5) FAILED(US"angle-brackets nested too deep");
			// parser.c:738| FAILED(US"domain missing in source-routed address");
			// parser.c:747| : string_sprintf("malformed address: %.32s may not follow %.*s",
			eb.ReCOMM: []string{ // SyntaxError
				"angle-brackets nested too deep",
				`expected word or "<"`,
				"domain missing in source-routed address",
				"malformed address:",
			},
			// route.c:1158|  DEBUG(D_uid) debug_printf("getpwnam() returned NULL (user not found)\n");
			eb.ReUSER: []string{"user not found"},
		}
		delayedfor := []string{
			// deliver.c:7475| "No action is required on your part. Delivery attempts will continue for\n"
			// smtp.c:3508|    US"retry time not reached for any host after a long failure period" :
			// deliver.c:7459| print_address_error(addr, f, US"Delay reason: ");
			"No action is required on your part",
			"retry time not reached for any host after a long failure period",
			"Delay reason: ",
		}

		if strings.Contains(bf.Payload, "\n----- This ") {
			// There are extremely rare cases where there are only five hyphens.
			// https://github.com/sisimai/set-of-emails/blob/master/maildir/bsd/lhost-exim-05.eml
			// ----- This is a copy of the message, including all the headers. ------
			bf.Payload = strings.Replace(bf.Payload, "\n----- This ", "\n------ This ", 1)
		}

		dscontents := make([]siba.DeliveryMatter, 1); v := &dscontents[0]
		emailparts := rfc5322.Part(&bf.Payload, boundaries, false)
		recipients := 0
		boundary00 := ""            // Boundary sting
		anotherone := []string{""}  // Keeping another error messages
		readcursor, nextcursor, rightindex := uint8(0), uint8(0), uint8(0)

		if bf.Headers["content-type"][0] != "" {
			// Get the boundary string and set regular expression for matching with the boundary string.
			boundary00 = rfc2045.Boundary(bf.Headers["content-type"][0], 0)
		}

		for e := range strings.Lines(emailparts[0]) {
			// Read error messages and delivery status lines from the head of the email to the
			// previous line of the beginning of the original message.
			e  = strings.TrimRight(e, "\n\r")
			if readcursor == 0 {
				// Beginning of the bounce message or message/delivery-status part
				for _, f := range startingof["message"] {
					// Check the message defined in startingof["message"], ["frozen"]
					if strings.Contains(e, f) == false { continue }
					readcursor |= HereIsDeliveryStatus

					// Goes to the next loop if the string does not contain "frozen" message
					if moji.ContainsAny(e, startingof["frozen"]) == false { continue }
				}
			}
			if readcursor & HereIsDeliveryStatus == 0 || e == "" { continue }

			// This message was created automatically by mail delivery software.
			//
			// A message that you sent could not be delivered to one or more of its
			// recipients. This is a permanent error. The following address(es) failed:
			//
			//  kijitora@example.jp
			//    SMTP error from remote mail server after RCPT TO:<kijitora@example.jp>:
			//    host neko.example.jp [192.0.2.222]: 550 5.1.1 <kijitora@example.jp>... User Unknown
			ce := false; switch {
				// Check whether the line matches the following conditions or not
				case strings.HasPrefix(e, "  ") == false:  // The line should start with "  " (2 spaces)
				case strings.IndexByte(e, '@') < 2:        // "@" should be included (email)
				case strings.IndexByte(e, '.') < 2:        // "." should be included (domain part)
				case strings.Contains(e, "pipe to |"):     // Exclude "pipe to /path/to/prog" line
				case e[2:3] == " ":                        // The 3rd character is " "
				case thirdparty == false && e[2:3] == "<": // MXLogic returns "  <neko@example.jp>: ..."
				default: ce = true
			}

			if cv := ""; ce == true || moji.ContainsAny(e, startingof["alias"]) {
				// The line is including an email address
				if moji.ContainsAny(e, startingof["alias"]) {
					// The line does not include an email address
					// deliver.c:4549|  printed = US"an undisclosed address";
					//   an undisclosed address
					//     (generated from kijitora@example.jp)
					cv = e[2:]

				} else {
					//   kijitora@example.jp
					//   sabineko@example.jp: forced freeze
					//   mikeneko@example.jp <nekochan@example.org>: ...
					cv = address.S3S4(moji.Select(e, "<", ">:", 0)); if cv != "" {
						// There are an email address and an error message in the line
						// parser.c:743| while (bracket_count-- > 0) if (*s++ != '>')
						// parser.c:744|   {
						// parser.c:745|   *errorptr = s[-1] == 0
						// parser.c:746|     ? US"'>' missing at end of address"
						// parser.c:747|     : string_sprintf("malformed address: %.32s may not follow %.*s",
						// parser.c:748|     s-1, (int)(s - US mailbox - 1), mailbox);
						// parser.c:749|   goto PARSE_FAILED;
						// parser.c:750|   }
						v.Diagnosis = moji.Select(e + moji.RHS, ">:", "", 0)

					} else {
						// There is an email address only in the line, such as "  kijitora@example.jp"
						// --- OR ---
						// "  kijitora@example.jp: forced freeze"
						p1 := strings.LastIndex(e, ": "); if p1 < 0 { p1 = len(e) }
						cv  = address.S3S4(e[2:p1])
					}
					if rfc5322.IsEmailAddress(cv) == false { continue }
				}

				if len(v.Recipient) > 0 && cv != v.Recipient {
					// There are multiple recipient addresses in the message body.
					v          = siba.NextDeliveryMatter(&dscontents)
					anotherone = append(anotherone, "")
					rightindex++
				}
				v.Recipient = cv
				recipients++

			} else if moji.ContainsAny(e, []string{" (generated from ", " generated by "}) {
				//     (generated from kijitora@example.jp)
				//  pipe to |/bin/echo "Some pipe output"
				//    generated by userx@myhost.test.ex
				for _, f := range strings.Split(e, " ") {
					// Get the alias adress
					if strings.IndexByte(f, '@') > 0 { v.Alias = address.S3S4(f); break }
				}
			} else {
				if moji.ContainsAny(e, startingof["frozen"]) {
					// Message *** has been frozen by the system filter.
					// Message *** was frozen on arrival by ACL.
					anotherone[rightindex] = e + " "

				} else if boundary00 != "" {
					// --NNNNNNNNNN-eximdsn-MMMMMMMMMM
					// Content-type: message/delivery-status
					// ...
					if rfc1894.Match(e) > 0 {
						// "e" matched with any field defined in RFC3464
						o := rfc1894.Field(e); if len(o) == 0 { continue }
						switch o[3] {
						default: v.Update(v.AsRFC1894(o[0]), o[2]) // Other DSN fields defined in RFC3464
						case "addr":
							// Final-Recipient: rfc822;|/bin/echo "Some pipe output"
							if o[0] != "final-recipient" || v.Spec != "" { continue }
							if strings.IndexByte(o[2], '@') > 0 { v.Spec = "SMTP" } else { v.Spec = "X-UNIX" }
						case "code":
							// Diagnostic-Code: SMTP; 550 5.1.1 <userunknown@example.jp>... User Unknown
							v.Spec      = strings.ToUpper(o[1])
							v.Diagnosis = o[2]
						}
					} else {
						// There are other error messages?
						if nextcursor > 0 { continue }
						switch {
							// Content-type: message/delivery-status
							case strings.HasPrefix(e, startingof["deliverystatus"][0]): nextcursor = 1
							case strings.HasPrefix(e, " "): anotherone[rightindex] += e + " "
						}
					}
				} else {
					// There is no boundary string in "boundary00"
					if len(dscontents) == recipients {
						// This line is an error message
						v.Diagnosis += " " + e

					} else if strings.HasPrefix(e, "  ") {
						// Error message when the email address above does not include '@' and 
						// domain part such as
						//   pipe to |/path/to/prog ...
						//     generated by kijitora@example.com
						v.Diagnosis += " " + e
					}
				}
			}
		}

		if recipients > 0 {
			// Check "an undisclosed address", "unroutable address"
			for j, _ := range dscontents {
				// Replace the recipient address with the value of "alias"
				e := &dscontents[j]
				if e.Alias == "" { continue }
				if strings.IndexByte(e.Recipient, '@') < 0 { e.Recipient = e.Alias }
			}
		} else if len(bf.Headers["x-failed-recipients"]) > 0 {
			// Fallback for getting recipient addresses
			// X-Failed-Recipients: kijitora@example.jp
			rcptinhead := strings.Split(bf.Headers["x-failed-recipients"][0], ",")
			recipients  = len(rcptinhead)

			for _, e := range rcptinhead {
				// Insert each recipient address into "dscontents"
				e = strings.Trim(e, " ")
				siba.TailDeliveryMatter(dscontents).Recipient = e
				if len(dscontents) != recipients { siba.NextDeliveryMatter(&dscontents) }
			}
		}
		if recipients == 0 { return nil }

		// Get the name of the local MTA
		// Received: from marutamachi.example.org (c192128.example.net [192.0.2.128])
		receivedby := bf.Headers["received"][len(bf.Headers["received"]) - 1]
		recvdtoken := rfc5322.Received(receivedby)

		for j, _ := range dscontents {
			// Check the error message, the rhost, the lhost, and the smtp command.
			e := &dscontents[j]

			if e.Diagnosis == "" && boundary00 != "" {
				// Empty Diagnostic-Code: or error message
				//
				// --NNNNNNNNNN-eximdsn-MMMMMMMMMM
				// Content-type: message/delivery-status
				//
				// Reporting-MTA: dns; the.local.host.name
				//
				// Action: failed
				// Final-Recipient: rfc822;/a/b/c
				// Status: 5.0.0
				//
				// Action: failed
				// Final-Recipient: rfc822;|/p/q/r
				// Status: 5.0.0
				e.Diagnosis = dscontents[0].Diagnosis
				if e.Spec        == "" { e.Spec = dscontents[0].Spec }
				if anotherone[0] != "" {
					if len(anotherone) <= j { anotherone = append(anotherone, "") }
					anotherone[j] = anotherone[0]
				}
			}

			if len(anotherone) > j && anotherone[j] != "" {
				// Copy alternative error message
				if e.Diagnosis == "" { e.Diagnosis = anotherone[j] }

				if strings.HasPrefix(e.Diagnosis, "-") || strings.HasSuffix(e.Diagnosis, "__") {
					// Override the value of diagnostic code message
					e.Diagnosis = anotherone[j]

				} else if len(e.Diagnosis) < len(anotherone[j]) {
					// Override the value of diagnostic code message with the value of alterrors
					// because the latter includes the former.
					anotherone[j] = strings.Join(strings.Fields(anotherone[j]), " ")
					if strings.Contains(strings.ToLower(anotherone[j]), strings.ToLower(e.Diagnosis)) {
						// anotherone[j] contains the same error message stored in e.Diagnosis
						e.Diagnosis = anotherone[j]
					}
				}
			}

			e.Diagnosis = strings.Join(strings.Fields(e.Diagnosis), " ")
			if cv := moji.Select(moji.LHS + e.Diagnosis, "", "__", 0); cv != "" { e.Diagnosis = cv }

			if e.Rhost   == "" { e.Rhost = rfc1123.Find(e.Diagnosis) }
			if e.Lhost   == "" { e.Lhost = recvdtoken[0] }
			if e.Command == "" {
				// Get the SMTP command name for the session
				for _, f := range startingof["command"] {
					// Find the last SMTP command from e.Diagnosis
					if strings.Contains(e.Diagnosis, f) == false              { continue }
					e.Command = command.Find(e.Diagnosis); if e.Command == "" { continue }
					break
				}

				// Detect the bounce reason by using the SMTP command
				switch e.Command {
				case eb.CeEHLO, eb.CeHELO: e.Reason = eb.ReBLOC // HELO | Connected to 192.0.2.135 but my name was rejected.
				case eb.CeMAIL:            e.Reason = eb.Re___1 // MAIL | Connected to 192.0.2.135 but sender was rejected.
				default:
					// Find any error message string defined in "messagesof" from e.Diagnosis
					for r := range messagesof {
						// The key is a bounce reason name
						if moji.ContainsAny(e.Diagnosis, messagesof[r]) { e.Reason = r; break }
					}
					if e.Reason == "" && moji.ContainsAny(e.Diagnosis, delayedfor) { e.Reason = eb.ReTIME }
				}
			}

			// Prefer the value of smtp reply code in Diagnostic-Code: field
			// See set-of-emails/maildir/bsd/exim-20.eml
			//
			//   Action: failed
			//   Final-Recipient: rfc822;userx@test.ex
			//   Status: 5.0.0
			//   Remote-MTA: dns; 127.0.0.1
			//   Diagnostic-Code: smtp; 450 TEMPERROR: retry timeout exceeded
			//
			// The value of "Status:" indicates permanent error but the value of SMTP reply code in
			// Diagnostic-Code: field is "TEMPERROR"!!!!
			e.ReplyCode = reply.Find(e.Diagnosis, e.Status)
			cv := ""; if failure.IsTemporary(e.ReplyCode) || e.Reason == eb.ReTIME {
				// Set the pseudo status code as a temporary error
				if reason.IsExplicit(e.Reason) { cv = status.Code(e.Reason, true) }
			}
			if e.Status == "" { e.Status = status.Prefer(cv, status.Find(e.Diagnosis, e.ReplyCode), e.ReplyCode) }
		}
		for emailparts[1] == "" {
			// There is no original message in the warning message like the follwing:
			//
			// This message was created automatically by mail delivery software.
			// A message that you sent has not yet been delivered to one or more of its
			// recipients after more than 24 hours on the queue on neko.example.com.
			//
			// The message identifier is:     neko222-nyaaan-22
			// The subject of the message is: Nyaan
			// The date of the message is:    Thu, 22 Apr 2016 23:34:45 +0900
			//
			// The address to which the message has not yet been delivered is:
			//
			//   kijitora@example.co.jp
			//     host mta-2.example.co.jp [192.0.2.222]
			//     Delay reason: SMTP error from remote mail server after MAIL FROM:<sironeko@neko.example.com> SIZE=1024:
			//     450 service permits 2 unverifyable sending IPs - neko.example.com is not 203.0.113.222
			//
			// No action is required on your part. Delivery attempts will continue for
			// some time, and this warning may be repeated at intervals if the message
			// remains undelivered. Eventually the mail delivery software will give up,
			// and when that happens, the message will be returned to you.
			emailparts[1] += "To: <" + dscontents[0].Recipient + ">\n"

			if cv := moji.Select(bf.Payload, "The date of the message is: ", "\n", 0); cv != "" {
				// The date of the message is:    Thu, 22 Apr 2016 23:34:45 +0900
				emailparts[1] += "Date: " + strings.Trim(cv, " ") + "\n"
			}
			if cv := moji.Select(bf.Payload, "The subject of the message is: ", "\n", 0); cv != "" {
				// The date of the message is:    Thu, 22 Apr 2016 23:34:45 +0900
				emailparts[1] += "Subject: " + strings.Trim(cv, " ") + "\n"
			}
		}
		return &siba.RisingUnderway{Digest: dscontents, RFC822: emailparts[1]}
	}
}

