// Copyright (C) 2024-2025 azumakuniyuki and sisimai development team, All rights reserved.
// This software is distributed under The BSD 2-Clause License.
//  _ _               _      _______          _                            ____   ___   ___ _____ 
// | | |__   ___  ___| |_   / / ____|_  _____| |__   __ _ _ __   __ _  ___|___ \ / _ \ / _ \___ / 
// | | '_ \ / _ \/ __| __| / /|  _| \ \/ / __| '_ \ / _` | '_ \ / _` |/ _ \ __) | | | | | | ||_ \ 
// | | | | | (_) \__ \ |_ / / | |___ >  < (__| | | | (_| | | | | (_| |  __// __/| |_| | |_| |__) |
// |_|_| |_|\___/|___/\__/_/  |_____/_/\_\___|_| |_|\__,_|_| |_|\__, |\___|_____|\___/ \___/____/ 
//                                                              |___/                             

package lhost
import "strings"
import "libsisimai.org/sisimai/v5/sis"
import "libsisimai.org/sisimai/v5/moji"
import "libsisimai.org/sisimai/v5/rfc5322"
import "libsisimai.org/sisimai/v5/smtp/status"

func init() {
	// InquireFor[*] decode bounce messages related to or generated by the MTA/ESP of the key name.
	//   Arguments:
	//     - bf (*sis.BeforeFact):  Message entity in progress
	//   Returns:
	//     - (*sis.RisingUnderway): A structure as a staging data that is processed in message.sift() function
	InquireFor["Exchange2003"] = func(bf *sis.BeforeFact) *sis.RisingUnderway {
		// - Microsoft Exchange Server 2003: https://www.microsoft.com/microsoft-365/exchange/email
		if bf == nil || bf.IsEmpty() == true { return nil }

		// X-MS-TNEF-Correlator: <00000000000000000000000000000000000000@example.com>
		// X-Mailer: Internet Mail Service (5.5.1960.3)
		// X-MS-Embedded-Report:
		proceedsto := false
		if len(bf.Headers["x-ms-embedded-report"]) > 0 { proceedsto = true }
		for proceedsto == false {
			// Check X-Mailer, X-MimeOLE, and Received headers
			tryto := []string{
				"Internet Mail Service (",                           // X-Mailer:
				"Microsoft Exchange Server Internet Mail Connector", // X-Mailer:
				"Produced By Microsoft Exchange",                    // X-MimeOLE:
				" with Internet Mail Service (",                     // Received:
			}
			if len(bf.Headers["x-mailer"]) > 0 {
				// X-Mailer:  Microsoft Exchange Server Internet Mail Connector Version 4.0.994.63
				// X-Mailer: Internet Mail Service (5.5.2232.9)
				if strings.HasPrefix(bf.Headers["x-mailer"][0], tryto[0]) { proceedsto = true; break }
				if strings.HasPrefix(bf.Headers["x-mailer"][0], tryto[1]) { proceedsto = true; break }
			}

			if len(bf.Headers["x-mimeole"]) > 0 {
				// X-MimeOLE: Produced By Microsoft Exchange V6.5
				if strings.HasPrefix(bf.Headers["x-mimeole"][0],tryto[2]) { proceedsto = true; break }
			}

			for _, e := range bf.Headers["received"] {
				// Received: by ***.**.** with Internet Mail Service (5.5.2657.72)
				if strings.Contains(e, tryto[3]) { proceedsto = true; break }
			}
			break
		}
		if proceedsto == false { return nil }

		boundaries := []string{"Content-Type: message/rfc822"}
		startingof := map[string][]string{
			"message": []string{"Your message"},
			"error":   []string{"did not reach the following recipient(s):"},
		}
		errorcodes := map[string][]string{
			"userunknown":  []string{"000C05A6", /* Unknown Recipient   */ },
			"filtered":     []string{"000C0595", /* Ambiguous Recipient */ },
			"systemerror":  []string{
				"00010256", // Too many recipients.
				"000D06B5", // No proxy for recipient (non-smtp mail?)
			},
			"networkerror": []string{
				"00120270", // Too Many Hops
			},
			"contenterror": []string{
				"00050311", // Conversion to Internet format failed
				"000502CC", // Conversion to Internet format failed
			},
			"securityerror":[]string{
				"000B0981", // 502 Server does not support AUTH
			},
			"onhold":       []string{
				"000B099C", // Host Unknown, Message exceeds size limit, ...
				"000B09AA", // Unable to relay for, Message exceeds size limit,...
				"000B09B6", // Error messages by remote MTA
			},
		}

		dscontents := make([]sis.DeliveryMatter, 1); v := &dscontents[0]
		rightindex := uint8(0)      // The last index number of dscontents
		emailparts := rfc5322.Part(&bf.Payload, boundaries, false)
		readcursor := uint8(0)      // Points the current cursor position
		recipients := uint8(0)      // The number of 'Final-Recipient' header
		statuspart := false         // Flag, true if it has read the delivery status part
		connvalues := 0             // Counter, 3 if it has got the all values of connheader
		connheader := [3]string{}   // [To:, Subject:, Date:]
		anotherone := []string{""}  // Keeping another error messages
		msexchange := []bool{false} // Flag, true if "MSEXCH:" text has been appeared

		for e := range strings.Lines(emailparts[0]) {
			// Read error messages and delivery status lines from the head of the email to the
			// previous line of the beginning of the original message.
			e  = strings.TrimRight(e, "\n\r")
			if readcursor == 0 {
				// Beginning of the bounce message or message/delivery-status part
				if strings.HasPrefix(e, startingof["message"][0]) { readcursor |= HereIsDeliveryStatus }
				continue
			}
			if readcursor & HereIsDeliveryStatus == 0 || statuspart == true { continue }

			if connvalues == len(connheader) {
				// did not reach the following recipient(s):
				//
				// kijitora@example.co.jp on Thu, 29 Apr 2007 16:51:51 -0500
				//     The recipient name is not recognized
				//     The MTS-ID of the original message is: c=jp;a= ;p=neko
				// ;l=EXCHANGE000000000000000000
				//     MSEXCH:IMS:KIJITORA CAT:EXAMPLE:EXCHANGE 0 (000C05A6) Unknown Recipient
				// mikeneko@example.co.jp on Thu, 29 Apr 2007 16:51:51 -0500
				//     The recipient name is not recognized
				//     The MTS-ID of the original message is: c=jp;a= ;p=neko
				// ;l=EXCHANGE000000000000000000
				//     MSEXCH:IMS:KIJITORA CAT:EXAMPLE:EXCHANGE 0 (000C05A6) Unknown Recipient
				if moji.Aligned(e, []string{"@", " on "}) {
					// kijitora@example.co.jp on Thu, 29 Apr 2007 16:51:51 -0500
					//   kijitora@example.com on 4/29/99 9:19:59 AM
					if len(v.Recipient) > 0 {
						// There are multiple recipient addresses in the message body.
						v          = sis.NextDeliveryMatter(&dscontents)
						anotherone = append(anotherone, "")
						msexchange = append(msexchange, false)
						rightindex++
					}
					cv := moji.Select(strings.ToLower(e), ":smtp=", "; on ", 0); if cv == "" {
						// c=US;a= ;p=neko;o=kijitora;cat:SMTP=NEKOCHAN@EXAMPLE.COM; on Fri, 4 Oct 2002
						cv = strings.TrimLeft(moji.Select(moji.LHS + e, "", " on ", 0), " ")
					}
					v.Recipient = cv
					recipients += 1
					msexchange[rightindex] = false

				} else if strings.HasPrefix(e, " ") && strings.Contains(e, "MSEXCH:") {
					//     MSEXCH:IMS:KIJITORA CAT:EXAMPLE:EXCHANGE 0 (000C05A6) Unknown Recipient
					v.Diagnosis += strings.TrimLeft(e, " ")

				} else {
					if msexchange[rightindex] == true { continue }
					if strings.HasPrefix(v.Diagnosis, "MSEXCH:") {
						// continued from the previous line starting with "MSEXCH:"
						msexchange[rightindex] = true
						statuspart   = true
						v.Diagnosis += " " + e

					} else {
						// Error messages in the body part
						anotherone[rightindex] += " " + e
					}
				}
			} else {
				// Your message
				//
				//  To:      shironeko@example.jp
				//  Subject: ...
				//  Sent:    Thu, 29 Apr 2010 18:14:35 +0000
				//
				if moji.HasPrefixAny(e, []string{"  To:  ", "      To: "}) {
					//  To:      shironeko@example.jp
					if connheader[0] != "" { continue }
					connheader[0] = moji.Select(e + moji.RHS, " To:", "", 0)
					connvalues++

				} else if moji.HasPrefixAny(e, []string{"      Subject: ", "  Subject: "}) {
					//  Subject: ...
					if connheader[1] != "" { continue }
					connheader[0] = moji.Select(e + moji.RHS, " Subject:", "", 0)
					connvalues++

				} else if moji.HasPrefixAny(e, []string{"  Sent: ", "      Sent: "}) {
					//  Sent:    Thu, 29 Apr 2010 18:14:35 +0000
					//  Sent:    4/29/99 9:19:59 AM
					if connheader[2] != "" { continue }
					connheader[0] = moji.Select(e + moji.RHS, " Sent:", "", 0)
					connvalues++
				}
			}
		}
		if recipients == 0 { return nil }

		for j, _ := range dscontents {
			// Tidy up the error message in e.Diagnosis, try to detect the bounce reason.
			e := &dscontents[j]
			e.Diagnosis = moji.Sweep(e.Diagnosis)

			if moji.Aligned(e.Diagnosis, []string{"MSEXCH:", "(", ")"}) {
				//     MSEXCH:IMS:KIJITORA CAT:EXAMPLE:EXCHANGE 0 (000C05A6) Unknown Recipient
				capturedcode := moji.Select(e.Diagnosis, "(", ")", 0)
				errormessage := moji.Select(e.Diagnosis + moji.RHS, ") ", "", 1)

				FINDREASON: for r := range errorcodes {
					// The key name is a bounce reason name
					for _, f := range errorcodes[r] {
						// Find the captured code from the error code table
						if capturedcode != f { continue }
						e.Reason = r
						e.Status = status.Code(r, false)
						break FINDREASON
					}
				}
				e.Diagnosis = errormessage
			}

			// Could not detect the reason from the value of "diagnosis", copy alternative error message 
			if e.Reason != "" || anotherone[j] == "" { continue }
			e.Diagnosis = moji.Sweep(anotherone[j] + " " + e.Diagnosis)
		}

		if emailparts[1] == "" {
			// When original message is not included in the bounce message
			bu := strings.Builder{}; bu.Grow(64)
			bu.WriteString("From: " + connheader[0] + "\n")
			bu.WriteString("Subject: " + connheader[2] + "\n")
			bu.WriteString("Date: " + connheader[1] + "\n")
			emailparts[1] += bu.String()
		}
		return &sis.RisingUnderway{Digest: dscontents, RFC822: emailparts[1]}
	}
}

