// Copyright (C) 2024-2026 azumakuniyuki and sisimai development team, All rights reserved.
// This software is distributed under The BSD 2-Clause License.
//  _ _               _      _____ __  __       _ _ ____                           
// | | |__   ___  ___| |_   / /_ _|  \/  | __ _(_) / ___|  ___ _ ____   _____ _ __ 
// | | '_ \ / _ \/ __| __| / / | || |\/| |/ _` | | \___ \ / _ \ '__\ \ / / _ \ '__|
// | | | | | (_) \__ \ |_ / /  | || |  | | (_| | | |___) |  __/ |   \ V /  __/ |   
// |_|_| |_|\___/|___/\__/_/  |___|_|  |_|\__,_|_|_|____/ \___|_|    \_/ \___|_|   

package lhost
import "strings"
import "libsisimai.org/sisimai/v5/eb"
import "libsisimai.org/sisimai/v5/siba"
import "libsisimai.org/sisimai/v5/moji"
import "libsisimai.org/sisimai/v5/address"
import "libsisimai.org/sisimai/v5/rfc5322"
import "libsisimai.org/sisimai/v5/smtp/command"

func init() {
	// InquireFor[*] decode bounce messages related to or generated by the MTA/ESP of the key name.
	//   Arguments:
	//     - bf (*siba.BeforeFact):  Message entity in progress.
	//   Returns:
	//     - (*siba.RisingUnderway): A structure as a staging data that is processed in message.sift() function.
	InquireFor["IMailServer"] = func(bf *siba.BeforeFact) *siba.RisingUnderway {
		// - Progress iMail Server: https://community.progress.com/s/products/imailserver
		// - X-Mailer: <SMTP32 v8.22>
		if bf == nil || bf.IsEmpty() == true { return nil }

		switch {
			case strings.HasPrefix(bf.Headers["subject"][0], "Undeliverable Mail "):
			case len(bf.Headers["x-mailer"]) > 0 && strings.HasPrefix(bf.Headers["x-mailer"][0], "<SMTP32 v"):
			default: return nil
		}

		boundaries := [][]byte{[]byte("Original message follows.")}
		startingof := map[string][]string{"error": []string{"Body of message generated response:"}}
		messagesof := map[string][]string{
			eb.ReUSER: []string{"Unknown user", "Invalid final delivery userid"},
			eb.ReTIME: []string{"Delivery failed "},
		}
		dscontents := make([]siba.DeliveryMatter, 1); v := &dscontents[0]
		emailparts := rfc5322.Part(bf.Payload, boundaries, false)
		mesgbuffer := strings.Builder{}; mesgbuffer.Grow(len(emailparts[0]) / 2)
		recipients := uint8(0)

		for e := range strings.Lines(emailparts[0]) {
			// Read error messages and delivery status lines from the head of the email to the
			// previous line of the beginning of the original message.
			e  = strings.TrimRight(e, "\n\r")
			if (strings.Index(e, ": ") > 8 && moji.Aligned(e, []string{": ", "@"})) || strings.HasPrefix(e, "undeliverable ") {
				// Unknown user: kijitora@example.com
				// undeliverable to kijitora@example.com
				if len(v.Recipient) > 0 { v = siba.NextDeliveryMatter(&dscontents) }
				v.Diagnosis = e
				v.Recipient = address.Find(e)[0]
				recipients += 1

			} else {
				// Other error messages
				if strings.Contains(e, startingof["error"][0]) {
					// Body of message generated response:
					mesgbuffer.WriteString(e)

				} else {
					// Error message after "Body of message generated response:" line
					if mesgbuffer.Len() > 0 { mesgbuffer.WriteString(" " + e) }
				}
			}
		}
		if recipients == 0 { return nil }

		alternates := mesgbuffer.String(); for j, _ := range dscontents {
			// Tidy up the error message in e.Diagnosis, Try to detect the bounce reason.
			e := &dscontents[j]

			e.Diagnosis = moji.Sweep(strings.ReplaceAll(alternates + " " + e.Diagnosis, "\n", " "))
			e.Command   = command.Find(e.Diagnosis)

			for r := range messagesof {
				// The key name is a bounce reason name
				// Try to find an error message including lower-cased string listed in messagesof
				if moji.ContainsAny(e.Diagnosis, messagesof[r]) { e.Reason = r; break }
			}
		}

		if strings.Contains(emailparts[1], "\nFrom: ") == false {
			// Set pseudo From: header into the original message
			emailparts[1] = "From: " + bf.Headers["to"][0] + "\n" + emailparts[1] + "\n"
		}
		if strings.Contains(emailparts[1], "\nTo: ") == false {
			// Set pseudo To: header into the original message
			emailparts[1] = "To: " + dscontents[0].Recipient + "\n" + emailparts[1] + "\n"
		}
		return &siba.RisingUnderway{Digest: dscontents, RFC822: emailparts[1]}
	}
}

