// Copyright (C) 2020,2024-2026 azumakuniyuki and sisimai development team, All rights reserved.
// This software is distributed under The BSD 2-Clause License.
//  ____  _____ ____ ____ _________  ____  
// |  _ \|  ___/ ___| ___|___ /___ \|___ \ 
// | |_) | |_ | |   |___ \ |_ \ __) | __) |
// |  _ <|  _|| |___ ___) |__) / __/ / __/ 
// |_| \_\_|   \____|____/____/_____|_____|

// Package "rfc5322" provides functions for email addresses, Date: header, Received: headers, and
// other headers and messages related to RFC5322. https://datatracker.ietf.org/doc/html/rfc5322
package rfc5322
import "libsisimai.org/sisimai/v5/moji"

var FieldIndex = []string{
	// The following fields are not referred in Sisimai
	// Resent-From Resent-Sender Resent-Cc Cc Bcc Resent-Bcc In-Reply-To References Comments Keywords
	"Resent-Date", "From", "Sender", "Reply-To", "To", "Message-ID", "Subject", "Return-Path", "Received",
	"Date", "X-Mailer", "Content-Type", "Content-Transfer-Encoding", "Content-Description", "Content-Disposition",
}
var HeaderTable = map[string][]string{
	"messageid": []string{"message-id"},
	"subject":   []string{"subject"},
	"listid":    []string{"list-id"},
	"date":      []string{"date", "osted-date", "posted", "resent-date"},
	"addresser": []string{
		"from", "return-path", "reply-to", "errors-to", "reverse-path", "x-postfix-sender",
		"envelope-from", "x-envelope-from",
	},
	"recipient": []string{
		"to", "delivered-to", "forward-path", "envelope-to", "x-envelope-to", "resent-to", "x-apparently-to",
	},
}

// The part of "Received:" headers generated by qmail or qmail-clone
//   - Received: (qmail 2202 invoked from network); 15 Oct 2015 06:22:22 -0000
//   - Received: (qmail 2220 invoked by uid 2); 17 Jul 2014 08:30:40 -0000
// Do not exclude the following strings:
//   - Received: (qmail 2204 invoked for bounce); 29 Apr 2010 00:00:00 -000
var woReceived = []string{" invoked by uid", " invoked from network"}

// LooksLikeEmail checks that the text looks like an email.
//   Arguments:
//     - mesg (*string): String to be checked that the text looks like an email.
//   Returns:
//     - (bool): true if the text may be an email.
func LooksLikeEmail(mesg *string) bool {
	if mesg == nil || len(*mesg) == 0 { return false }

	// - The first 1000 bytes should be a plain text.
	// - LF or CR or CRLF should be included in the first 1000 bytes.
	// - The header and body must be separated by a double line break: "\n\n", "\r\n\r\n", or "\r\r".
	le, cw := len(*mesg), 1000; if le < cw { cw = le - 1 }
	cv     := (*mesg)[:cw]

	if moji.IsText(mesg)                                             == false { return false }
	if moji.ContainsAny(cv, []string{"\n", "\r", "\r\n"})            == false { return false }
	if moji.ContainsAny(*mesg, []string{"\n\n", "\r\n\r\n", "\r\r"}) == false { return false }
	return true
}

