// Copyright (C) 2020,2024 azumakuniyuki and sisimai development team, All rights reserved.
// This software is distributed under The BSD 2-Clause License.
package lhost
import "strings"

// OrderBySubject() returns an MTA Order decided by the first word of the "Subject": header.
func OrderBySubject(title string) []string {
	// @param   [string] title Subject header string
	// @return  [[]string]     Order of MTA functions
	if len(title) == 0 { return []string {} }

	table := map[string][]string {
		"abuse-report":          []string{"ARF"},
		"auto":                  []string{"RFC3834"},
		"auto-reply":            []string{"RFC3834"},
		"automatic-reply":       []string{"RFC3834"},
		"aws-notification":      []string{"AmazonSES"},
		"complaint-about":       []string{"ARF"},
		"delivery-failure":      []string{"Domino", "X2"},
		"delivery-notification": []string{"MessagingServer" },
		"delivery-report":       []string{"PowerMTA" },
		"delivery-status":       []string{"GoogleGroups", "McAfee", "OpenSMTPD", "AmazonSES", "AmazonWorkMail", "Gmail", "X3"},
		"dmarc-ietf-dmarc": []string{"ARF"},
		"email-feedback":   []string{"ARF"},
		"failed-delivery":  []string{"X2"},
		"failure-delivery": []string{"X2"},
		"failure-notice":   []string{"Yahoo", "qmail", "mFILTER", "Activehunter", "X4"},
		"loop-alert":       []string{"FML"},
		"mail-could":       []string{"InterScanMSS"},
		"mail-delivery":    []string{"Exim", "GMX", "EinsUndEins", "Zoho", "MXLogic"},
		"mail-failure":     []string{"Exim"},
		"mail-not":         []string{"X4"},
		"mail-system":      []string{"EZweb"},
		"message-delivery": []string{"MailFoundry"},
		"message-frozen":   []string{"Exim"},
		"non-recapitabile": []string{"Exchange2007"},
		"non-remis":        []string{"Exchange2007"},
		"notice":           []string{"Courier"},
		"permanent-delivery": []string{"X4"},
		"postmaster-notify":  []string{"Sendmail"},
		"returned-mail": []string{"Sendmail", "V5sendmail", "Biglobe", "X1"},
		"there-was":     []string{"X6"},
		"undeliverable": []string{"Office365", "Exchange2007", "Exchange2003"},
		"undeliverable-mail":    []string{"MailMarshalSMTP", "IMailServer"},
		"undeliverable-message": []string{"Notes", "Verizon"},
		"undelivered-mail":      []string{"Postfix", "Zoho"},
		"warning":               []string{"Sendmail", "Exim"},
	}

	// The following order is decided by the first 2 words of Subject: header
	title = strings.Replace(title, "[", " ", -1)
	title = strings.Replace(title, "]", " ", -1)
	title = strings.Replace(title, "_", " ", -1)

	// Squeeze duplicated space characters
	for strings.Contains(title, "  ") { title = strings.ReplaceAll(title, "  ", " ") }

	title  = strings.TrimSpace(title)           // Remove leading space characters
	words := strings.SplitN(strings.ToLower(title), " ", 3)
	first := ""

	if strings.Index(words[0], ":") > 0 {
		// Undeliverable: ..., notify: ...
		first = strings.ToLower(title[0:strings.Index(words[0], ":")])

	} else {
		// Postmaster notify, returned mail, ...
		first = strings.Join(words[0:2], "-")
	}

	first = strings.ReplaceAll(first, `:`, "")
	first = strings.ReplaceAll(first, `,`, "")
	first = strings.ReplaceAll(first, `*`, "")
	first = strings.ReplaceAll(first, `"`, "")
	return table[first]
}

// AnotherOrder() returns MTA functions list as a spare
func AnotherOrder() []string {
	// @param
	// @return  [[]string] Ordered MTA functions list
	return []string {
		// There are another patterns in the value of "Subject:" header of a bounce mail generated by
		// the following MTA/ESP functions
		"Exim", "Sendmail", "Office365", "Exchange2007", "Exchange2003",
		"AmazonWorkMail", "AmazonSES", "InterScanMSS", "KDDI", "SurfControl", "Verizon",
		"ApacheJames", "X2", "X5", "FML",

		// The following is a fallback list
		"Postfix", "Yahoo", "GMX", "MessagingServer", "EinsUndEins", "Domino",
		"Notes", "qmail", "Courier", "OpenSMTPD", "Zoho", "MXLogic", "MailFoundry",
		"McAfee", "V5sendmail", "mFILTER", "PowerMTA", "GoogleGroups",
		"Gmail", "EZweb", "IMailServer", "MailMarshalSMTP", "Activehunter", "Biglobe",
		"X4", "X1", "X3", "X6",
	}
}

