// Copyright (C) 2024-2025 azumakuniyuki and sisimai development team, All rights reserved.
// This software is distributed under The BSD 2-Clause License.
//  ____  _____ ____ _____ _  _    __   _  _     _______         _ ____            _         
// |  _ \|  ___/ ___|___ /| || |  / /_ | || |   / /___ / _ __ __| |  _ \ __ _ _ __| |_ _   _ 
// | |_) | |_ | |     |_ \| || |_| '_ \| || |_ / /  |_ \| '__/ _` | |_) / _` | '__| __| | | |
// |  _ <|  _|| |___ ___) |__   _| (_) |__   _/ /  ___) | | | (_| |  __/ (_| | |  | |_| |_| |
// |_| \_\_|   \____|____/   |_|  \___/   |_|/_/  |____/|_|  \__,_|_|   \__,_|_|   \__|\__, |
//                                                                                     |___/ 

package rfc3464
import "strings"

var ReturnedBy = make(map[string]func(string) []string, 1)
var thirdparty = map[string][]string{
//	"Aol":      []string{"X-Outbound-Mail-Relay-"}, // X-Outbound-Mail-Relay-(Queue-ID|Sender)
	"PowerMTA": []string{"X-PowerMTA-"},            // X-PowerMTA-(VirtualMTA|BounceCategory)
//	"Yandex":   []string{"X-Yandex-"},              // X-Yandex-(Queue-ID|Sender)
}

// is3rdparty returns true if the argument is a line generated by a MTA that has fields defined in
// RFC3464 inside of a bounce mail the MTA returns.
//   Arguments:
//     - (field string): Line of a bounce mail.
//   Returns:
//     - (bool): The line indicates that a bounce mail generated by the 3rd party MTA.
func is3rdparty(field string) bool {
	if field == "" || returnedby(field) == "" { return false }
	return true
}

// returnedby returns an MTA name of the 3rd party.
//   Arguments:
//     - field (string): Line of a bounce mail.
//   Returns:
//     - (string): The MTA name of the 3rd party.
func returnedby(field string) string {
	if field == "" || strings.HasPrefix(field, "X-") == false { return "" }
	for e := range thirdparty {
		// Does the argument include the 3rd party specific field?
		if strings.HasPrefix(field, thirdparty[e][0]) { return e }
	}
	return ""
}

// xfield returns rfc1894.Field() compatible slice for the specific field of the 3rd party MTA.
//   Arguments:
//     - field (string): Line of the error message.
//   Returns:
//     - ([]string): []string{"field-name", "value-type", "value", "field-group", "comment"}
func xfield(field string) []string {
	if field == "" { return []string{} }
	if party := returnedby(field); party != "" { return ReturnedBy[party](field) }
	return []string{}
}

