// Copyright (C) 2020,2024-2025 azumakuniyuki and sisimai development team, All rights reserved.
// This software is distributed under The BSD 2-Clause License.
//  _____          _   
// |  ___|_ _  ___| |_ 
// | |_ / _` |/ __| __|
// |  _| (_| | (__| |_ 
// |_|  \__,_|\___|\__|

// Package "siba" provides types for data structure of sisimai
// SIBA stands for Sisimai Internal Bounce Abstraction.
package siba

import "time"
import "encoding/json"

type Fact struct {
	Action          string       `json:"action"`         // The value of "Action:" field
	Addresser       EmailAddress `json:"addresser"`      // The sender address of the original message
	Alias           string       `json:"alias"`          // The alias of the recipient address
	Catch           interface{}  `json:"catch"`          // Results generated by the user-defined callback function[1]
	Command         string       `json:"command"`        // The last SMTP command
	DecodedBy       string       `json:"decodedby"`      // MTA module name
	DeliveryStatus  string       `json:"deliverystatus"` // "Status:" field value or the delivery status such as "5.2.2"
	Destination     string       `json:"destination"`    // The domain part of the "Recipient"
	DiagnosticCode  string       `json:"diagnosticcode"` // "Diagnostic-Code:" field value or error messages in the message body
	DiagnosticType  string       `json:"diagnostictype"` // The subtype of "Diagnostic-Code:" field such as "SMTP", "X-UNIX"
	FeedbackID      string       `json:"feedbackid"`     // The value of Feedback-ID: header of the original message
	FeedbackType    string       `json:"feedbacktype"`   // Feedback Type, always empty except when the Reason is Feedback
	HardBounce      bool         `json:"hardbounce"`     // Hard bounce or not: true, false
	Lhost           string       `json:"lhost"`          // The hostname of the local mail server (the server attempting to send the email).
	ListID          string       `json:"listid"`         // The value of "List-Id" field of the original message
	MessageID       string       `json:"messageid"`      // The value of "Message-Id:" header of the original message
	Origin          string       `json:"origin"`         // The path of the bounce mail as a data source
	Reason          string       `json:"reason"`         // The Bounce reason name, which sisimai detected
	Rhost           string       `json:"rhost"`          // The hostname of the remote mail server (the server intended to receive the email).
	Recipient       EmailAddress `json:"recipient"`      // The recipient address of the original message
	ReplyCode       string       `json:"replycode"`      // SMTP Reply Code such as "421", which is picked from the error message
	SenderDomain    string       `json:"senderdomain"`   // The domain part of the "Addresser"
	Subject         string       `json:"subject"`        // The value of Subject: header of the original message
	Timestamp       time.Time    `json:"timestamp"`      // Unix machine time(int64) of that the email bounced
	TimezoneOffset  string       `json:"timezoneoffset"` // Time zone offset of "Timestamp", such as "+0900"
	Token           string       `json:"token"`          // The Message token(MD5 Hex digest value)
}

// Fact.MarshalJSON returns a lower-cased member name converted from a field name defined in RFC1894.
//   Returns:
//     - ([]byte): JSON string.
//     - (error):  Occurred error.
func(fa Fact) MarshalJSON() ([]byte, error) {
	type AnotherOne Fact // To avoid an infinite loop
	return json.Marshal(&struct {
		Addresser string `json:"addresser"`
		Recipient string `json:"recipient"`
		Timestamp int64  `json:"timestamp"`
		AnotherOne
	}{
		Addresser:  (fa).Addresser.Address,
		Recipient:  (fa).Recipient.Address,
		Timestamp:  (fa).Timestamp.Unix(),
		AnotherOne: (AnotherOne)(fa),
	})
}

// Fact.Dump() returns a serialized siba.Fact{} structure as a JSON string.
//   Returns:
//     - (string): JSON string.
//     - (error):  Occurred error.
func(fa Fact) Dump() (string, error) {
	jsonb, nyaan := json.Marshal(fa); if nyaan != nil { return "", nyaan }
	return string(jsonb), nil
}

