name: golangci-lint

on:
- push
- pull_request

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: >
            address arf fact lda lhost mail message moji reason
            rfc1123 rfc1894 rfc2045 rfc3464 rfc3834 rfc5322 rfc5965 rfc791
            rhost sis smtp/command smtp/failure smtp/reply smtp/status smtp/transcript

