name: make test
on:
  push:
    branches: ["5-stable"]
  pull_request:
    branches: ["*"]
jobs:
  maketest:
    name: Make Test with Go 
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: ["1.24.0", "1.26.6"]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
      - run:  go mod tidy
      - run:  go build -v ./...
      - run:  make -f Developers.mk test

